### ISSUE TITLE
Custom posts bbPress not outputting tags in source code

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1297] opened 2017-10-12 00:59 UTC
Reported here on the support forum:
https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/does-not-work-for-bbpress-replies/

**Comment by michaeltorbert** [comment] 2017-10-12 01:46
This may be a duplicate of #202

**Comment by arnaudbroes** [comment] 2017-10-12 20:35
@michaeltorbert I've tested bbPress with All in One SEO Pack (starting from 2.0) and it seems that Replies have never been supported before. There's three different custom post types: Forums, Topics and Replies, and it's just that last one that doesn't output any meta tags at all.

**Comment by contactashish13** [comment] 2017-10-16 06:33
@michaeltorbert I tested this and I'm confused - Forums and Topics have their own pages i.e. can be viewed on their own page but Replies are a subset of the Topic and have no page of their own so I'm not sure if this can be supported. Example: the forum can be viewed http://wordpress-118694-338656.cloudwaysapps.com/forums/forum/ddddd/ and the topic http://wordpress-118694-338656.cloudwaysapps.com/forums/topic/tipoc/ and the reply is just a named anchor in the topic: http://wordpress-118694-338656.cloudwaysapps.com/forums/topic/tipoc/

**Comment by arnaudbroes** [comment] 2017-10-16 12:25
@contactashish13 Replies do get a page of their own, as you can see here for example:
http://wordpress-111082-347208.cloudwaysapps.com/forums/reply/23

Follow these steps:
#1. Add a new Forum
#2. Add a new Topic and mark the Forum page as parent
#3. View the topic and do a reply on it.
#4. Now go to Replies in the WordPress backend. You'll see something like this: "Reply to: XXXX". 
Now take a look at that post. You'll see that it gets its own URL and outputs different tags in the source code.

**Comment by contactashish13** [comment] 2017-10-16 13:04
@arnaudbroes The view link gives "http://wordpress-118694-338656.cloudwaysapps.com/forums/topic/tipoc/#post-18251" as the URL as you can see in the screenshot below

![image](https://user-images.githubusercontent.com/12953439/31613358-7ca084b8-b2a0-11e7-9d6d-736a1fb744e4.png)

**Comment by arnaudbroes** [comment] 2017-10-16 13:07
@contactashish13 
Go to the Edit Screen of the Reply and then click the URL above.
![image](https://user-images.githubusercontent.com/18156697/31613551-bb30ceb2-b283-11e7-9959-6b50d260588c.png)
I'm not sure why the URL on the Replies directory is different.

**Comment by contactashish13** [comment] 2017-10-16 13:09
@arnaudbroes got it!

**Comment by contactashish13** [comment] 2017-10-17 06:17
@michaeltorbert I may have found the problem. The meta tags are being added by determining what type of content is being loaded. For this we use is_single(), is_category(), is_page() etc. methods. Replies are comments to topics so they do not qualify as is_single() even when their own single page is loaded. They are in fact identified by is_singular(). I can add support for this but I don't know what else could be inadvertently supported because of this change.

**Comment by michaeltorbert** [comment] 2017-10-18 00:44
@contactashish13 What is your recommendation?

**Comment by contactashish13** [comment] 2017-10-18 11:29
@michaeltorbert its a fine balance between tying the plugin tightly to bbpress by using its functions/hooks vs. keeping it generic. But maybe for the short term we can go with the first method. What do you suggest?

**Comment by contactashish13** [comment] 2017-10-21 14:40
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1319

**Closed** 2018-10-12 19:06 UTC
Labels: Bug
