### ISSUE TITLE
IE freeze on editing post/page, just for editors

### ISSUE THREAD

**Issue by drmab** [semperfiwebdesign/all-in-one-seo-pack#3069] opened 2019-12-03 16:03 UTC
Please fill out this form as completely as possible so that we can help you more quickly.

- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**
When an editor, using IE, tries to edit a page or post in WP 5.3, whether with the block editor or the classic one, the browser freezes entirely.

**To Reproduce**
1. Make sure you have WP 5.3, and AIOSEO 3.3.3
2. Using IE 11, log in as a user with an editor role
3. From the back-end, try to edit a post or page

**Expected behavior**
To be able to edit without the browser freezing

**Version Info (please complete the following information):**
 - WordPress version: 5.3
 - All in One SEO Pack version: 3.3.3
 - PHP version: 7.1

**Additional context**
Doesn't happen for administrators, or on Chrome or Firefox (not tested on Safari)

**Comment by wpsmort** [comment] 2019-12-03 17:32
@drmab This may be related to #3050 but if you can send us an Administrator login for your site using the secure form below then we can confirm this:

https://semperplugins.com/contact/support-login-information/

**Comment by arnaudbroes** [comment] 2020-01-09 14:00
Duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3102.

@drmab we have reproduced and identified the issue and will ship a fix with the next release.

**Closed by arnaudbroes** 2020-01-09 14:00 UTC
Labels: Bug, Needs Reproducing, Needs User Input, User Reported
