### ISSUE TITLE
possible bug in exporter

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#450] opened 2016-08-26 22:53 UTC
I've only tested this in pro, but it's likely in free as well

The export file is named "admin.php" and contains the message "</span> Warning: Header may not contain more than a single header, new line detected in /app/public/wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_importer_exporter.php on"

**Comment by michaeltorbert** [comment] 2016-08-26 23:05
@arnaudbroes Can you verify this exists in free, and what version it started?

**Comment by arnaudbroes** [comment] 2016-08-27 11:57
I'll take a look this evening.

**Comment by arnaudbroes** [comment] 2016-08-27 15:43
@michaeltorbert 
When did you encounter this?
I tested this with different versions (both Pro and Free), a new WP configuration and the SemperPlugins dev website and I didn't find it a single time in the admin.php file.

**Comment by michaeltorbert** [comment] 2016-08-31 19:25
This has been reported by a user today. @arnaudbroes see if you can reproduce it and determine when it started. 

<img width="593" alt="2016- 08-31 22 12 10" src="https://cloud.githubusercontent.com/assets/17364998/18143206/102ccda0-6f8f-11e6-893a-7dee5f4d65a6.png">

**Comment by arnaudbroes** [comment] 2016-09-20 08:14
@michaeltorbert 
Still not able to reproduce it. Any leads?

**Comment by wpsmort** [comment] 2016-10-07 16:51
I was able to reproduce the error in the admin.php file today on my Pressmatic Dev site running the current dev branch.  I'm going to see if I can reproduce this on a new site.

<img width="1322" alt="screen-capture" src="https://cloud.githubusercontent.com/assets/17548525/19198329/955a6518-8c8c-11e6-8b63-7992319cdd40.png">

**Comment by wpsmort** [comment] 2016-10-07 23:05
This was introduced in this commit which was for WP standards refactoring - https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/ff6c27d86ccacbb3922fd24dc04d41d93c0cf446#diff-1ae830d4237572e3eb3ae5f3f7faabe8

**Comment by wpsmort** [comment] 2016-10-07 23:06
This is now fixed.

**Closed by wpsmort** 2016-10-07 23:06 UTC
Labels: Bug, Needs Testing, PRIORITY - High
