### ISSUE TITLE
Improve question mark dashicon

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1865] opened 2018-08-27 14:13 UTC
Look at how we can change the size/location of the question mark dashicon in order to improve UX

**Comment by EkoJR** [comment] 2018-08-27 16:44
This may be slightly different, but I believe #289 (use dashicons as much as possible to save space) improves this by converting the help icon to a Dashicon. Which also converts it SVG (required for Icons), and causes the icon to scale better.

**Comment by michaeltorbert** [comment] 2018-08-27 17:08
@EkoJR  Feel free to prove me wrong, but I was thinking it already was a dashicon.

**Comment by EkoJR** [comment] 2018-08-27 17:44
It appears that is correct, I may have been thinking of an earlier version. Although, I meant it as a custom Dashicon/Fonticon; which seemed to have potential at the time with customization, and got added.

**Comment by wpsmort** [comment] 2019-03-07 21:27
This is a dupe of #1918

**Closed by wpsmort** 2019-03-07 21:27 UTC
Labels: UX
