### ISSUE TITLE
Custom post type content showing in posts tags / cats

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#396] opened 2016-07-09 14:51 UTC
Reported here: https://wordpress.org/support/topic/custom-post-type-content-showing-in-posts-tags-cats?replies=1#post-8619435

See if we can verify this. Since this deals with tag/category SEO meta, is this a pro-specific issue?

**Comment by arnaudbroes** [comment] 2019-02-18 00:20
This would have been a Pro issue, but I'm not able to reproduce it anyway. Based on the original report, I suspect this was caused by a plugin or theme conflict so I'll close the issue.

**Closed by arnaudbroes** 2019-02-18 00:21 UTC
Labels: Couldn't reproduce
