### ISSUE TITLE
Undefined variable in 404 error page

### ISSUE THREAD

**Issue by jguerine** [semperfiwebdesign/all-in-one-seo-pack#1801] opened 2018-07-26 22:00 UTC
Hello,

I've noticed that my 404 error page briefly shows an error message before the page.
It says "Undefined variable: post_type in : /xxxxxxxxxxxxxxxxxx/plugins/all-in-ones-seo-pack/aioseop_class.php on line 4159

**Comment by wpsmort** [comment] 2018-07-26 22:15
Duplicate of #1798

**Closed by wpsmort** 2018-07-26 22:15 UTC
