### ISSUE TITLE
Noindex/nofollow tag not output when taxonomy is empty

### ISSUE THREAD

**Issue by githubeing** [semperfiwebdesign/all-in-one-seo-pack#2075] opened 2018-11-21 06:50 UTC
**Describe the bug**
The option `use noindex for categories` doesn't work for categories that contain no published entries.

**To Reproduce**
1. In the General Settings , enable option `use noindex for categories` as it's described [here](https://semperplugins.com/documentation/noindex-settings/)
2. Create a category e.g. `test`
3. Optionally, you may add some entries to this category, but only those ones that aren't published yet, so that the category page will remain empty ("nothing found")
4. Open category page e.g. `https://my-site.com/categories/test/`
5. View source code

**Expected behavior**
There is something like this in the code:
```
<!-- All in One SEO Pack 2.9.1 by Michael Torbert of Semper Fi Web Design[178,210] -->
<meta name="robots" content="noindex,follow" />
```

**Actual behavior**
There is no such tag.

**Additional context**
If you then add some public blog entries to that category, then the tag will appear in the code, if you remove them, it'll disappear again.

**Comment by arnaudbroes** [comment] 2018-11-21 07:17
@githubeing thank you for reporting this.

I've confirmed that this is a bug and that it also applies to nofollow. Marking categories as noindex/nofollow in the meta box on the Edit page also doesn't work. Changing the title to better reflect the issue.

**Comment by wpsmort** [comment] 2018-11-21 13:46
I don't believe there is a bug here.  If a taxonomy does not have any published posts then you get a 404 Not Found page when viewing the taxonomy archive.  You cannot view a taxonomy archive unless there is at least one published post.  I verified this on a brand new install of WordPress and followed the steps to reproduce and I got a 404 page when viewing the category archive.

**Comment by arnaudbroes** [comment] 2018-11-21 15:22
Steve and I troubleshooted the issue together and confirmed that it is an actual bug since empty taxonomy pages aren't 404 pages, but actually exist.

**Comment by githubeing** [comment] 2018-11-21 16:49
the thing is even more interesting. I confirm that on an empty new wordpress instance (after creating the `test` category) the URL `http://wordpress-4_9_8/category/test/` returns a 404 page "OOPS! THAT PAGE CAN’T BE FOUND" (with http 404 status code) BUT when you change theme from `twenty seventeen` to e.g. `twenty fifteen` then the same page returns "NOTHING FOUND" with 200 http status code. even if you switch back to `twenty seventeen` theme, it still returns 200 code. while some non-existent category returns 404 e.g. `http://wordpress-4_9_8/category/non-existent/` does.

**Comment by githubeing** [comment] 2018-11-21 16:50
therefore, i think this is a bug in wordpress itself since it doesn't behave consistently between switching themes immediately after install and after the first switch.

**Comment by githubeing** [comment] 2018-11-21 17:04
i think wordpress should always return a 200 code on empty category. it shouldn't be 404 because the category itself does exist, therefore its status should differ from a non-existent category which should return 404. therefore, i think that this is a bug of all-in-one-seo-pack that it doesn't apply `noindex` to these empty 200 pages. do you agree?

**Comment by githubeing** [comment] 2018-11-21 17:34
i've created a bug report on wordpress for this (only for wordpress' itself fault), will see if they will confirm that
https://core.trac.wordpress.org/ticket/45393

**Comment by wpsmort** [comment] 2018-11-21 17:40
@githubeing Thanks for creating the bug report on WordPress Trac.  We'll look into outputting NOINDEX and NOFOLLOW tags on empty taxonomy archives.

**Comment by githubeing** [comment] 2018-12-18 17:48
I confirm that in version 2.10 the bug doesn't reproduces anymore. 👍 Thanks!

**Comment by arnaudbroes** [comment] 2018-12-18 18:43
I've confirmed that this bug is now fixed. @githubeing thank you for your cooperation.

**Closed by arnaudbroes** 2018-12-18 18:43 UTC
Labels: Bug, Has been reproduced
