### ISSUE TITLE
google analytics script updates

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1296] opened 2017-10-11 20:03 UTC
For some reason, in PR #931, we removed a version of the GA tracking code.

@amostajo 
@wpsmort 

Any idea why? 

This suggests we should have it https://developers.google.com/analytics/devguides/collection/analyticsjs/
and it's requested here: https://wordpress.org/support/topic/google-analytics-not-working-17/

User says _Google tag assistant states error to be “no HTTP response detected”_

I see the documentation at https://github.com/googleanalytics/autotrack#installation-and-usage but should it be optional?

---------------------

`(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){		 +
 -			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),		 +				ga('send', 'pageview');
 -			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)		
 -			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');		
 -		
 -			ga('create', '{$analytics_id}'{$domain}{$js_options});		
 -			{$extra_options}		
 -			ga('send', 'pageview');`

**Comment by michaeltorbert** [comment] 2017-10-13 12:54
Update from user:

"the issue was having the website URL entered in the Tracking Domain settings of this All In One SEO plugin (bug?). Remove the URL in the Tracking Domain box and GA will work."

**Comment by wpsmort** [comment] 2018-10-26 22:42
It looks like Google has changed their analytics tracking code yet again.  It now looks like they use Global Site Tag (gtag.js) tracking code which looks like this:

`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123456789-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123456789-1');
</script>`

**Comment by michaeltorbert** [comment] 2019-03-13 20:05
@wpsmort Can you please review this for 2019?

**Comment by wpsmort** [comment] 2019-03-19 18:31
I have reviewed this and here are my findings and recommendations.

Google has added a new version of their tracking code called Global Site Tag (gtag.js).  This is the recommended tracking method for all new implementations of Google Analytics.

However, they do still support the Universal Analytics (analytics.js) code which we currently output.  This explains the available options - https://support.google.com/analytics/answer/7538414#analyticsjs

The code we output now is correct and fine.  We output the alternative async tracking code here - https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet.  We do this so that we can use the Autotrack.js plugin for advanced tracking features (#921).

I recommend we implement the newer Global Site Tag (gtag.js) for basic users and Google Tag Manager for advanced users.  See issues #1386 and #2302.

**Comment by wpsmort** [comment] 2019-03-19 20:06
I'm closing this as I cannot reproduce the issue with the Tracking Domain setting and we've not received any other reports of a problem with that setting.

**Closed by wpsmort** 2019-03-19 20:06 UTC
Labels: Initial Review, Priority | High, User Reported
