### ISSUE TITLE
placeholder not going away

### ISSUE THREAD

**Issue by henrihappy** [semperfiwebdesign/all-in-one-seo-pack#3054] opened 2019-11-19 15:24 UTC
antiquedutchclockparts.nl

The issue is that there is a placeholder in adding a new product, that doesn’t go away in text mode it is for the field product name. Many people have researched the mistake and ended up with your code as being the one that is causing the placeholder error and Advanced customs pro field for the mistake the site goes dark, but both are somehow related as well.

The mistake has been researched by;

Woocommerce that says: (continue under it)

Henri,
The site wasn't working because there is some terrible coding practices in the theme's functions.php
On line 38 of functions.php is a call to acf_add_options_page(); - that function is provided, I assume, by the advanced custom fields plugin. What this means is that if the theme is active and the advanced custom fields plugin is not active, we end up with fatal errors such as:
Uncaught Error: Call to undefined function acf_add_options_page() in /var/www/vhosts/telemet.net/antiquedutchclockparts.nl/wp-content/themes/freestore-child-theme/functions.php:38
and can be seen in the error log that WooCommerce keeps here: https://antiquedutchclockparts.nl/wp-admin/admin.php?page=wc-status&tab=logs&log_file=fatal-errors-2019-11-18-27f18cc259f954d5a49424d6f15985bc.log
I would suggest you contact whoever maintains the code in the theme's functions.php and let them know this needs to be corrected.
On to the problem of the placeholder remaining when it shouldn't, I was able to reproduce this behavior. See screencast:
https://cld.wthms.co/pRNmnM
I then deactivated all plugins except for WooCommerce and switched to the Storefront theme. Under those conditions, this is no longer reproducible. See screencast:
https://cld.wthms.co/GWwVSV
My guess is that this is a theme issue and I would suggest you contact the theme's support team for assistance.

****I contacted the theme creator and he is responsible for the screenshot you seen of the code gone wrong, this is what he further had to say:**** 

Ok, the issue is the All in One SEO Pack plugin.

If you deactivate that plugin then it will work.

The plugin has errors on the product page which is causing the issues, see the image attached.
You need to contact the developers of the All in One SEO Pack plugin and let them know that their plugin has javascript errors which is causing the placeholder issue.

The Advanced Custom Pro problem is, as WooCommerce support said, because there is an advanced custom pro function calling, but it's has not got the plugin so it's an issue with the advanced custom pro plugin, you maybe need to ask those developers about that.

None of these are theme related and all plugins are separate developers so you'll need to contact each separately.

Hope that helps :)

<img width="433" alt="Screen Shot 2019-11-19 at 9 25 30 AM (002)" src="https://user-images.githubusercontent.com/57466781/69159902-e7733900-0ae8-11ea-9c0a-8e873c1db19e.png">

**Comment by henrihappy** [comment] 2019-11-19 19:19
needs reproducing is something required from me?

**Comment by wpsmort** [comment] 2019-11-19 19:24
@henrihappy I've tried to reproduce the console errors you are getting on the Add New Product screen in WooCommerce but I cannot reproduce this.  Can you please send us a login for your site using the secure form below so we can reproduce this on your site:

https://semperplugins.com/contact/support-login-information/

**Comment by wpsmort** [comment] 2019-11-19 19:57
@henrihappy Thank you for the login for your site.  However, I cannot reproduce those console errors on your site.  If I go to the Add New Product screen there are no console errors.  If I then enter some text in the Product Name field and click Save Draft I still don't get any errors.  See screenshot below:

<img width="2560" alt="Screen Shot 2019-11-19 at 2 55 21 PM" src="https://user-images.githubusercontent.com/17548525/69181273-cd335e00-0adc-11ea-910b-7ac57ca212a3.png">

Can you please provide the exact steps to reliably reproduce this on your site.

**Comment by henrihappy** [comment] 2019-11-19 20:02
you have to start in text mode in visual there is no problem, the placeholder only stays in place in texct mode. If you start in visual mode and then switch to text mode it also works. You got to set it to text then go to another page to start "fresh" then go to the page and start entering in the placeholder product name and you should see it then.

**Comment by wpsmort** [comment] 2019-11-19 20:07
@henrihappy I have now been able to reproduce this on your site and on a test site here.  We'll look into what's causing these JavaScript errors and fix them in the next release which is currently in development.

**Comment by wpsmort** [comment] 2019-11-19 20:12
I'm closing this in favor of #3052 as it's the same bug.

**Closed by wpsmort** 2019-11-19 20:12 UTC
Labels: Bug, Has been reproduced, User Reported

**Comment by henrihappy** [comment] 2019-12-20 10:03
Hi,

 

It is a very annoying bug, when can the update with fix be expected? 

 

Henri

 

Van: wpsmort [mailto:notifications@github.com] 
Verzonden: dinsdag 19 november 2019 21:08
Aan: semperfiwebdesign/all-in-one-seo-pack <all-in-one-seo-pack@noreply.github.com>
CC: henrihappy <henri@telemet.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [semperfiwebdesign/all-in-one-seo-pack] placeholder not going away (#3054)

 

@henrihappy <https://github.com/henrihappy>  I have now been able to reproduce this on your site and on a test site here. We'll look into what's causing these JavaScript errors and fix them in the next release which is currently in development.

**Comment by wpsmort** [comment] 2019-12-20 16:47
@henrihappy The fix was released today - https://semperplugins.com/all-in-one-seo-pack-changelog/
