### ISSUE TITLE
Investigate possible canonical issue on paged archives

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#438] opened 2016-08-18 12:15 UTC
Reported here https://wordpress.org/support/topic/unusual-404-errors-created-by-aioseo?replies=1

**Comment by michaeltorbert** [comment] 2016-08-19 18:50
Some themes have a secondary query (new WP_Query) which won't work with pagination. This was reported with the 15zine theme.

To replicate the issue, add a static page with their "builder" template. In their builder, toggle on the latest posts. This will break pagination for posts on that page.

We should still be able to detect the pagination and compensate, but we need to decide:
a) if we want to (this isn't how WP intends pagination/latest posts to work) and 
b) whether we should try and detect it by default, or via API hook

**Comment by michaeltorbert** [comment] 2016-08-19 23:01
We should also investigate whether this issue exists with any page builder plugins

**Comment by michaeltorbert** [comment] 2016-08-22 15:58
Since this can generally be resolved with the user of our API's filter hook for canonical (and prev/next as appropriate), I'm reducing the priority to "low".
We should determine if this is even common enough with the most used themes/plugins that have builder functionality that we'd want to make a change in AIOSEOP core.

**Comment by arnaudbroes** [comment] 2019-08-18 12:03
I couldn't reproduce this with over multiple popular themes nor with any popular page builders so I'm going to close this issue considering that:

1. This has not been reported ever since;
2. This is more of a theme issue; 
3. This can be fixed through our filter hook;
4. This would be extremely low priority;
5. Our canonical code needs an overhaul anyway.

**Closed by arnaudbroes** 2019-08-18 12:03 UTC
Labels: Priority | Low, User Reported, Won't Fix
