### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Aftex** [semperfiwebdesign/all-in-one-seo-pack#1536] opened 2018-01-30 12:14 UTC
Warning: count(): Parameter must be an array or an object that implements Countable in xxxxxxxxxxxx/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 2661

php 7.2

**Comment by EkoJr** [comment] 2018-01-30 18:19
Duplicate of #1491

**Comment by Aftex** [comment] 2018-01-30 18:30
when will be updated in the WordPress plugin?

**Closed** 2018-01-30 19:03 UTC
