### ISSUE TITLE
JSON-LD Syntax error: value, object or array expected.

### ISSUE THREAD

**Issue by shomichiru** [semperfiwebdesign/all-in-one-seo-pack#2780] opened 2019-08-04 09:37 UTC
I am getting Uncategorized Errors in [Google Structured Data Testing Tool ](https://search.google.com/structured-data/testing-tool/u/0) after updating to version 3.2.1.

\# code example
```
...
<script type="application/ld+json" class="aioseop-schema">performance.mark("inline-js-1-start");{"@context":"https://schema.org","@graph":[{"@type":["Person","Organization"],"@...
```
If __performance.mark("inline-js-1-start");__ code is removed and validated, no error will be generated.

Now, [Schema Settings]> [Use Schema.org Markup] has been disabled on the WordPress 5.2.2 Admin Page.

**Comment by wpsmort** [comment] 2019-08-04 14:50
@shomichiru Please provide the URL that you tested in the Structured Data Testing Tool.

**Comment by shomichiru** [comment] 2019-08-04 15:32
@wpsmort It's  https://www.iffthen.com. 
Thanks.

**Comment by wpsmort** [comment] 2019-08-04 15:40
@shomichiru This is not caused by our plugin.  Something in your site is injecting that performance inline-js everywhere that there is JavaScript.  If you search the page source code of your homepage for inline-js-1 you'll see what I mean.  

As we're not outputting that, I'm closing this issue.

**Closed by wpsmort** 2019-08-04 15:40 UTC
