### ISSUE TITLE
No support for < WP 4.6

### ISSUE THREAD

**Issue by enaimi** [semperfiwebdesign/all-in-one-seo-pack#2174] opened 2019-01-30 16:39 UTC
Immediately after upgrading from 2.10.1 to 2.11 server returns error 500  

PHP Fatal error:  Call to undefined function wp_get_attachment_caption() in /var/www/[domain]/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_sitemap.php on line 3502, referer: [domain]/wp-admin/index.php?page=aioseop-about

Notice that - 
I have 2 websites (2 separate WP installs ) under the same domain. one of them is in English which works fine with the new version, and the other one is in Hebrew and the update leads to the error mentioned above

**Comment by wpsmort** [comment] 2019-01-30 16:41
@enaimi Can you send us an Administrator login for your site and FTP login for your server using the secure form here please - https://semperplugins.com/contact/support-login-information/

**Comment by enaimi** [comment] 2019-01-30 16:51
Since I'm part of an organization that has a restricted network policy, access from outside our network is highly complicated to arrange... is there anything else I can do instead?

**Comment by wpsmort** [comment] 2019-01-30 16:53
@enaimi This may be something that can be resolved by enabling Sitemap Indexes and setting the Maximum Posts Per Sitemap Page to something such as 1000 (https://semperplugins.com/documentation/xml-sitemaps-module/#enable-sitemap-indexes).  Can you try that and see if it resolves the 500 error please.

**Comment by wpsmort** [comment] 2019-01-30 17:01
@enaimi What version of WordPress do you have?

**Comment by enaimi** [comment] 2019-01-30 17:09
I believe it is already enabled. please see attached screenshots
although the file is empty http://1062fm.co.il/he/sitemap.xml

![2019-01-30_190118](https://user-images.githubusercontent.com/47187008/51998526-86c73100-24c1-11e9-9478-998ec1f6e659.jpg)
![2019-01-30_190012](https://user-images.githubusercontent.com/47187008/51998527-86c73100-24c1-11e9-922c-70f9e8361698.jpg)


WP version is 4.4.4 but like I said... the English version of this website is works with the update. 

I''ve noticed that the change log says:
XML Sitemap – improved special characters encoding
Fix for Japanese language

So... although I really know nothing about this... my guess would be that this might have something to do with Hebrew characters or RTL lang... something like that...?

Thanks

**Comment by EkoJR** [comment] 2019-01-30 17:22
This was introduced before 2.11 (not sure exactly when yet), and wasn't introduced in WP until 4.6.

There could be some form of backwards compatibility, but looking at the function it's just a post excerpt being wrapped.
https://developer.wordpress.org/reference/functions/wp_get_attachment_caption/

...and could probably change the code to use the excerpt instead.

**Comment by wpsmort** [comment] 2019-01-30 17:36
@enaimi The problem is that we have code in our XML Sitemap which only works with WordPress v4.6 or later.  You're running WP v4.4.4 which is why you're getting that error.  We'll look to see if we can add backwards compatibility but we do intend on changing our minimum required version of WordPress to v4.5 very soon (#1568).  

I recommend you update your version of WordPress to at least 4.6 if not later.

**Comment by enaimi** [comment] 2019-01-30 17:37
Well... your last post got me to think...

What would happen if I'll "Exclude images" and then update the version... Because it says something about attachments.

![2019-01-30_192946](https://user-images.githubusercontent.com/47187008/52000458-d1e34300-24c5-11e9-9ebe-5b6a49d157cd.jpg)

So I excluded images 
And then I updated
And the update was successful

Then I thought... maybe now I can "un-exclude" and somehow now it works 

The weirdest thing :)

**Comment by wpsmort** [comment] 2019-01-30 17:45
@enaimi There's only a certain amount of time that we can continue to support older versions of WordPress such as 4.4.  You'll find this with many other plugins.

**Comment by enaimi** [comment] 2019-01-30 17:49
OK I understand
Anyway... for now everything works. 
I appreciate the effort!

**Comment by michaeltorbert** [comment] 2019-01-31 06:01
Since wp_get_attachment_caption() is such a small and simple function, offhand I'd say we could simply just make our wp_get_attachment_caption, checking if the core one exists first, with a note to remove it once we don't support <4.6.

On the other hand, considering 4.6 came out 2.5 years ago, we may want to consider dropping support for <4.6.

**Comment by michaeltorbert** [comment] 2019-02-13 16:42
After some discussion it was agreed that we'd drop support for < WP 4.6.

**Closed by michaeltorbert** 2019-02-13 16:42 UTC
Labels: Bug, In Development
