### ISSUE TITLE
Bug - $requested_page is not an object (robots-meta.php)

### ISSUE THREAD

**Issue by icjq** [semperfiwebdesign/all-in-one-seo-pack#3015] opened 2019-11-12 03:19 UTC
in pagination of homepage, I get error notice that $requested_page is not an object
in /inc/general/aioseop-robots-meta.php line 132 and line 136

**Comment by arnaudbroes** [comment] 2019-11-12 07:39
@icjq thank you for reporting this. Is your paginated homepage a regular Page or is it a special kind of page like a WooCommerce Shop page?

**Comment by icjq** [comment] 2019-11-12 07:42
Hello,


is a Regular Page.


I noticed that several people also reflected the same problem, not just me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arnaud Broes"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午3:39
收件人:&nbsp;"semperfiwebdesign/all-in-one-seo-pack"<all-in-one-seo-pack@noreply.github.com&gt;;
抄送:&nbsp;"大火船"<stanleychan007@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [semperfiwebdesign/all-in-one-seo-pack] $requested_page is not an object (#3015)




@icjq thank you for reporting this. Is your paginated homepage a regular Page or is it a special kind of page like a WooCommerce Shop page?

**Comment by arnaudbroes** [comment] 2019-11-12 07:44
> It's a regular page. I noticed that several people also reflected the same problem, not just me.

Thank you for your prompt response. 

We'll try to reproduce this on our end and get a bug fix out ASAP. In the meanwhile, you might want to disable WP_DEBUG in your wp-config.php file so that the error is no longer displayed on your frontpage.

**Comment by icjq** [comment] 2019-11-12 07:45
Hello,


is a Regular Page.


I noticed that several people also reflected the same problem, not just me.


I have solved the problem by edit the file as below:


all-in-one-seo-pack/inc/general/aioseop-robots-meta.php


if (is_object($requested_page)){
&nbsp; &nbsp; &nbsp;if ( property_exists( $requested_page, 'ID' ) ) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $meta = get_post_meta( $requested_page-&gt;ID );
&nbsp; &nbsp; &nbsp;}


&nbsp; &nbsp; &nbsp;if ( property_exists( $requested_page, 'term_id' ) ) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $meta = get_term_meta( $requested_page-&gt;term_id );
&nbsp; &nbsp; &nbsp;}
}



------------------ 原始邮件 ------------------
发件人:&nbsp;"Arnaud Broes"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午3:39
收件人:&nbsp;"semperfiwebdesign/all-in-one-seo-pack"<all-in-one-seo-pack@noreply.github.com&gt;;
抄送:&nbsp;"大火船"<stanleychan007@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [semperfiwebdesign/all-in-one-seo-pack] $requested_page is not an object (#3015)




@icjq thank you for reporting this. Is your paginated homepage a regular Page or is it a special kind of page like a WooCommerce Shop page?

**Comment by icjq** [comment] 2019-11-12 07:48
WP_DEBUG has been defined as false, but the error still displayed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arnaud Broes"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午3:44
收件人:&nbsp;"semperfiwebdesign/all-in-one-seo-pack"<all-in-one-seo-pack@noreply.github.com&gt;;
抄送:&nbsp;"大火船"<stanleychan007@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [semperfiwebdesign/all-in-one-seo-pack] Bug - $requested_page is not an object (robots-meta.php) (#3015)



 
It's a regular page. I noticed that several people also reflected the same problem, not just me.
  
Thank you for your prompt response.
 
We'll try to reproduce this on our end and get a bug fix out ASAP. In the meanwhile, you might want to disable WP_DEBUG in your wp-config.php file so that the error is no longer displayed on your frontpage.

**Comment by arnaudbroes** [comment] 2019-11-12 07:55
> WP_DEBUG has been defined as false, but the error still displayed.

Gotcha. We'll try and get a bug fix out today.

**Comment by michaeltorbert** [comment] 2019-11-12 14:38
Closing as a duplicate of #3014

**Closed** 2019-11-12 14:37 UTC
Labels: Bug, Duplicate, Needs Reproducing
