### ISSUE TITLE
WooCommerce upgrade notice won't go away when clicking "no thanks" or close

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2556] opened 2019-06-04 11:28 UTC
Reported here: https://wordpress.org/support/topic/warning-msg-asking-to-upgrade-annoying

## To Reproduce

This will need 2 users. 1 as the main admin, the other as an Editor.

1. Go to Settings > Reading and enable "Discourage search engines from indexing this site" to trigger `blog_public_disabled`.
2. Browse admin as the site admin to set WC notice.
3. With notice displayed, click 'No thanks' to delay notice.
4. In a different browser (or log out and log in as editor), browse site as an Editor. (the bug would trigger a reset)
5. Go back other user, and browse as site admin. Notice displays when it should not appear.

**Comment by arnaudbroes** [comment] 2019-06-04 14:28
I was not able to reproduce this.

**Comment by michaeltorbert** [comment] 2019-06-04 14:29
We'll need access to someone's site who is experiencing the problem.

**Comment by Justabandit** [comment] 2019-06-05 19:28
Whats the resolution to this apart from you closing opened issues

**Comment by michaeltorbert** [comment] 2019-06-05 19:29
@Justabandit We're not simply closing open issues. You opened a duplicate issue. 
The resolution to this is in the merged PR for 3.0.2 linked on this issue.

**Comment by michaeltorbert** [comment] 2019-06-06 00:26
https://wordpress.org/support/topic/upgrade-nag-message-for-woocommerce-users/#post-11609995

Reported here that the problem is still there.

**Comment by wpsmort** [comment] 2019-06-06 13:39
I had a services customer email yesterday to report this. He's not agreed to allow us access to his site.  However, he reported that the notice was gone last night but didn't say what he did to get rid of it. 

This morning he emailed to say that the notice is back on WooCommerce screens but gone from Jetpack screens.  He had dismissed the notice on the Jetpack Stats screen by clicking the X.  He's hosted on SiteGround and has cleared the SG cache.

I'm still trying to get him to give us access so we can take a look.

**Comment by EkoJR** [comment] 2019-06-07 00:30
I believe this may be occurring when multiple users have access to wp-admin, but don't have `manage_options` perms. Which causes the notice to deactivate, and to later be reactivated by site admin.

**Comment by EkoJR** [comment] 2019-06-07 07:32
Confirmed this bug was being triggered by non-admins browsing the wp-admin side. Which would explain why it was difficult to reproduce.

It requires testing with 2 or more accounts, 1 as admin, and other(s) as non-admin.

**Comment by michaeltorbert** [comment] 2019-06-07 19:37
One user just reported his site only has admins.

**Closed** 2019-06-08 01:49 UTC
Labels: Has PR, Needs User Input, Priority | High, User Reported
