### ISSUE TITLE
Update prevents me from editing my home page

### ISSUE THREAD

**Issue by andrewst123** [semperfiwebdesign/all-in-one-seo-pack#3061] opened 2019-11-25 04:25 UTC
I just updated to the latest version and I can no longer edit my home page.  It takes forever to load and I get mutliple timeout messages, and then when it finishes loading no links work and I can't click on anything.  If I restore to before this update, everything works properly.  I've tried restoring and updating again and the same issues occur.  Something is wrong with this update!

**Comment by arnaudbroes** [comment] 2019-11-25 09:38
@andrewst123 please post the URL of your homepage here; otherwise we can't be of much help. Off-hand I'd say you're an experiencing an issue we are aware of where the Preview Snippet is impacting performance if you have a lot of content (characters/words) for that page. We've already developed a fix for this and will be releasing it soon.

**Comment by andrewst123** [comment] 2019-11-25 10:05
Website is https://makingthemusic.com

I have lots of thumbnails in the photo collection found on the home page. 

Regards,
Andrew St. Hilaire
www.makingthemusic.com
(204) 955-8496

**Comment by wpsmort** [comment] 2019-11-25 19:32
@andrewst123 Can you please send us an Administrator login for your site and FTP login for your web server using the secure form below and we can take a look:

https://semperplugins.com/contact/support-login-information/

**Comment by andrewst123** [comment] 2019-11-25 22:08
No, I don’t feel comfortable providing you with admin access to my site.

 

Regards,

Andrew St. Hilaire

www.makingthemusic.com

(204) 955-8496

**Comment by wpsmort** [comment] 2019-11-25 22:43
@andrewst123 Can you clone the site to create a test site we can access?  Without access to your site where we can see the problem we can't troubleshoot this.  This

**Comment by andrewst123** [comment] 2019-11-25 22:47
This is your problem, not mine.  No, I’ve informed you of the issue.

 

Regards,

Andrew St. Hilaire

www.makingthemusic.com

(204) 955-8496

**Comment by arnaudbroes** [comment] 2019-11-26 10:56
@andrewst123 we can't fix something we can't reproduce, so I'm closing this.

**Closed by arnaudbroes** 2019-11-26 10:56 UTC
Labels: Needs User Input, User Reported
