### ISSUE TITLE
Autogenerate Descriptions does not work

### ISSUE THREAD

**Issue by aleks683** [semperfiwebdesign/all-in-one-seo-pack#1321] opened 2017-10-21 18:46 UTC
Autogenerate Descriptions does not work if there is a picture in front of the text. Example:

```
<img src="https://static-global-s-msn-com.akamaized.net/img-resizer/tenant/amp/entityid/AAtMTIk.img" />
Here any text of the article
```
In this case it does not work Autogenerate Descriptions.

**Comment by arnaudbroes** [comment] 2017-10-21 18:54
Related to #1103?

**Comment by aleks683** [comment] 2017-10-21 19:36
The problem is urgent. It's not about plugins. And not in the subject. Removal of the `&nbsp;` does not help either. Autogenerated OG Descriptions works perfectly. What to do?

**Comment by michaeltorbert** [comment] 2017-10-23 02:17
I'm closing this as a duplicate of #1308. 
@aleks683 I'll ask you to please not post the same message in multiple issues. I'm removing it from the other.

**Closed by michaeltorbert** 2017-10-23 02:17 UTC
Labels: Duplicate
