### ISSUE TITLE
"Calling parse_str() without the result argument is deprecated"

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1880] opened 2018-09-04 21:52 UTC
Reported on 9/4/2018 at 4:16 PM EST. 
Error can be found at https://www.thebrooklandscars.co.uk/sitemap.xml.

@michaeltorbert, can you review this and confirm we just need to add a second, result argument in order to fix this?

**Comment by michaeltorbert** [comment] 2018-09-04 22:00
That's correct, this is as of PHP 7.2 according to https://secure.php.net/manual/en/function.parse-str.php

**Comment by EkoJR** [comment] 2018-09-06 21:37
This problem only affects the Pro Version with the Video Sitemap feature.

In regards to the initial report, I've been unable to reproduce the exact same error, and the sitemap was still operating. Also, the variable was being set as null instead of throwing an error. 

Tested on PHP 7.2.4

**Comment by michaeltorbert** [comment] 2018-09-06 23:53
Closing in favor of the Pro issue.

**Closed by michaeltorbert** 2018-09-06 23:53 UTC
Labels: In Development
