### ISSUE TITLE
bug in 2.7.3 ?

### ISSUE THREAD

**Issue by gingeralfie** [semperfiwebdesign/all-in-one-seo-pack#1868] opened 2018-08-28 14:02 UTC
A 404 error page also throws up "Notice: Undefined variable: post_type in [...] wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 4159"

**Comment by michaeltorbert** [comment] 2018-08-28 14:04
Dupe of #1798

**Closed by michaeltorbert** 2018-08-28 14:04 UTC
