### ISSUE TITLE
remove publisher/author tag

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1696] opened 2018-05-21 03:39 UTC
These haven't been supported by Google since 2014. Is there any reason why we should still have them?

https://semperplugins.com/documentation/google-settings/

**Comment by arnaudbroes** [comment] 2018-05-25 20:52
I don't think so. Some people are even complaining about the fact that we still output it.

**Comment by wpsmort** [comment] 2019-03-18 19:55
Dupe of #2121

**Closed by wpsmort** 2019-03-18 19:55 UTC
Labels: Initial Review
