### ISSUE TITLE
Social Meta Module - Add support for the og:locale tag

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#104] opened 2016-03-31 13:57 UTC
Add support for og:locale - https://developers.facebook.com/docs/opengraph/guides/internationalization

We could take the og:locale from the Site Language setting in WordPress and offer a drop down to select a different locale.  We could also consider including an advanced option to select multiple locales as og:locale:alternate.

**Comment by michaeltorbert** [comment] 2017-03-16 14:03
Closing as a dupe of #737

**Closed by michaeltorbert** 2017-03-16 14:03 UTC
Labels: Collaborate, Enhancement, Priority - Low
