### ISSUE TITLE
Undefined variable: post_type in aioseop_class.php

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1798] opened 2018-07-19 05:15 UTC
`Undefined variable: post_type in <b>/var/www/fournais-bender.dk/public_html/wp-content/plugins/all-in-one-seo-pack-pro/aioseop_class.php</b> on line <b>4155</b>`

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L4159

Reported by Henriette via email. 

For reproducing... on the customer's site, it's only showing up on the _search results_ page.

**Comment by wpsmort** [comment] 2018-07-26 22:16
@jguerine Can you please send us an Administrator login for your site using the secure form below so we can troubleshoot this:

https://semperplugins.com/contact/support-login-information/

**Comment by michaeltorbert** [comment] 2018-08-02 03:41
Reported for category archive pages: https://wordpress.org/support/topic/notice-undefined-variable-error-on-archive-page/

**Comment by awgd** [comment] 2018-08-06 19:14
If you intended to use $post_type on line 4159 of the aioseop_class then you will need to include 'global $post_type;' somewhere before it to be able to use it. Since the comment above it says it is duplicated to prevent stepping on toes, not sure if it's even needed or not.

**Comment by michaeltorbert** [comment] 2018-08-07 23:29
This code was added in https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/ebf2c686fa106e9d0aa908ec68d12ef297780b17 by @contactashish13

**Comment by contactashish13** [comment] 2018-08-08 06:07
to reproduce:

1. Default to NOFOLLOW: checked for posts
2. Use noindex for Categories: checked
3. Go to category archive page

PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1825

**Comment by wpsmort** [comment] 2018-08-13 21:27
@contactashish13 I tested this PR by following your steps above.  Whilst this does fix the undefined variable notice it incorrectly changes the nofollow meta tag on category archives.  It changes the nofollow to match the setting for Posts which is wrong.

**Comment by jguerine** [comment] 2018-08-21 18:35
I checked on my website.

It appeared on the 404 pages, for which I had ticked "noindex" in the AIO options. 
I unticked that option for the 404 pages, and the error disappear.

I ticked again, and the error reappear.

It does indeed seems (to me) that it would come from that!

**Comment by contactashish13** [comment] 2018-08-22 06:08
@wpsmort The problematic code was introduced to fix https://github.com/semperfiwebdesign/aioseop-pro/issues/322. Can you please reconcile the behavior of this bug and https://github.com/semperfiwebdesign/aioseop-pro/issues/322 so that I can test comprehensively?

**Comment by wpsmort** [comment] 2018-08-27 17:27
@contactashish13 I tested this thoroughly.  The change made in your PR does not affect the fix for https://github.com/semperfiwebdesign/aioseop-pro/issues/322.  It does not reintroduce that bug.

The only bug that your PR introduces is the change in behavior as stated in my comment above - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-414691103

**Comment by arnaudbroes** [comment] 2018-09-07 21:44
Reported again today by Dorte via e-mail.

**Comment by arnaudbroes** [comment] 2018-09-11 12:49
FYI, Steve found out earlier that the PHP notice on the front-end of the website is there because of the WooCommerce PDF Invoices & Packing Slips plugin. Disabling the "Debug output" setting under PDF Invoices > Status resolves this.

**Comment by michaeltorbert** [comment] 2018-09-11 13:09
Reported here: https://wordpress.org/support/topic/updated-to-2-8-still-see-undefined-variable-error-line-4181/

**Comment by contactashish13** [comment] 2018-09-14 08:59
@arnaudbroes so is this still a bug or not?

**Comment by JWestarp** [comment] 2018-09-14 10:35
I've got this problem, too. (Version 2.8)

**Comment by arnaudbroes** [comment] 2018-09-14 19:42
@contactashish13 it is.

**Comment by contactashish13** [comment] 2018-09-15 06:57
@arnaudbroes please share a copy of that plugin on slack.

**Comment by arnaudbroes** [comment] 2018-09-15 09:58
@contactashish13 what plugin? There's no specific plugin causing this as far as we know. There are some plugins though that have debugging features which we disable for our customers in order to remove the error notice as a temp fix.

**Comment by contactashish13** [comment] 2018-09-15 12:39
@arnaudbroes according to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-420262265 this happens when a specific option in a specific option is chosen.  That is the plugin I'm requesting. If you are talking about the bug mentioned in this issue, it was fixed in the PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1825. Can you confirm that that PR fixes this?

The other issue reported by @wpsmort in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-416302394  and I don't have clarity about the next steps.

**Comment by michaeltorbert** [comment] 2018-09-15 17:26
Also reported here (with a list of plugins installed) https://wordpress.org/support/topic/updated-to-2-8-still-see-undefined-variable-error-line-4181/#post-10690989

**Comment by contactashish13** [comment] 2018-10-03 05:33
@wpsmort I was able to reproduce the scenario mentioned in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-414691103

The difference is because `post_type` was not defined in 2.7.3 (the bug we are trying to fix) and therefore it does not qualify in the condition that checks whether the current post type should have `nofollow`. 

But when I fix the bug, `post_type` is now defined as `post` and this satisfies the condition because we have `nofollow checked for posts`. That is why the `follow` directive becomes `nofollow`. According to the  preexisting code, this is the correct behavior. Let me know if you feel that is incorrect and also mention the correct behavior. You may need to create a different issue.

PS - This piece of code is complex and even a slight modification can cause changes to ripple over to other conditions. A bug fix is more than likely to cause another bug which we will not catch unless we can create comprehensive test cases. It might be helpful to have a comprehensive listing of all scenarios so that a unit test can be created.

**Comment by wpsmort** [comment] 2018-10-03 21:03
@contactashish13 Thanks for the information.  We can't push a bug fix that changes behavior so we need to look at other options here which may require rewriting this code.  

Are you sure there's no other code change you can make here that would fix this Undefined variable error without changing the behavior of the noindex and nofollow meta tags?

If you're unable to find a solution to this that doesn't change the behavior of these meta tags then we'll need to look at a careful rewrite of the code.  This would ensure we can fix a number of the behavior problems with these settings and determine what options we need (there are no options for NOFOLLOW categories, tags, etc.).  This will require a broader discussion before committing to a rewrite.

**Comment by contactashish13** [comment] 2018-10-04 13:55
@wpsmort my changes that introduced this bug were for https://github.com/semperfiwebdesign/aioseop-pro/issues/322. In that issue, because of the immensely complicated code, I had to duplicate the code so that I didn't mess up any other functionality. In fact my code comment also reads `#322: duplicating this code so that we don't step on some other entities' toes.`.  

I'm trying to reconcile the behavior of that issue with the current issue and I'm unable to make sense of it in terms of what combination of options causes what combination of follow/index. It might be helpful if you could make a grid that will make testing (and creation of unit tests) easier. We might just have to rewrite the whole code again.

**Comment by wpsmort** [comment] 2018-10-15 21:29
@contactashish13 I have created a spreadsheet which lists the current behavior and the correct expected behavior of the NOINDEX and NOFOLLOW settings.  I have shared it with you via Google Docs.  Please let me know if you have any questions.

**Comment by wpsmort** [comment] 2018-10-16 13:44
I'm pushing this out to 3.1 as this likely requires a rewrite of the code for NOINDEX and NOFOLLOW settings.

**Comment by psmits1567** [comment] 2018-11-05 10:29
Hi
Got the same error 
Undefined variable: post_type in /www/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 4253
 ( ( '' === $aiosp_nofollow ) && ( ! empty( $aioseop_options['aiosp_cpostnofollow'] ) ) && in_array( $post_type, $aioseop_options['aiosp_cpostnofollow'] ) )
Seems within this function the variable $post_type is empty !
Latest version of SEO 2.9.1.

**Comment by peteralewis** [comment] 2019-03-15 11:49
For me this was appearing on the 404 page, unticking "Use noindex for the 404 page:" from AIOSEO settings resolved the error output. I still have `<meta name="robots" content="noindex,follow">` output to the page, so still OK.

**Comment by psmits1567** [comment] 2019-03-15 12:35
Thanks peter, I will test it

**Comment by arnaudbroes** [comment] 2019-03-23 15:19
Reported again here - https://wordpress.org/support/topic/a-new-undefined-variable/

**Comment by marsuby** [comment] 2019-04-25 13:01
Same here: Undefined variable post_type in aioseop_class.php on line 4249
... it's only showing up on the search results page.

**Comment by wpsmort** [comment] 2019-04-26 15:21
Reported again here https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/error-log-why-is-this-error-happening/

**Comment by arnaudbroes** [comment] 2019-06-05 10:40
@psmits1567 believes this might fix the issue:
[If I add the following on line 4246 the error is no longer present:
$post_type = get_post_type();](url)

**Comment by arnaudbroes** [comment] 2019-06-22 15:02
Reported again here - https://wordpress.org/support/topic/aioseop_class-php-on-line-3983/

**Comment by JanSudek** [comment] 2019-06-24 06:46
still have notice `Notice Undefined variable: post_type in file /wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 3983` on 404 Not found page... 
AIOSP v3.1.1
WP v4.9.10

**Comment by arnaudbroes** [comment] 2019-06-24 07:38
@JanSudek we're actively working on a fix.

**Closed** 2019-07-24 17:54 UTC
Labels: Bug, Has PR, Priority | High, User Reported

**Comment by michaeltorbert** [comment] 2019-07-24 17:56
Props and 🌮to all involved in finally getting this issue resolved. 
@arnaudbroes
