### ISSUE TITLE
top level menu icon flickers from gear to shield on pageload

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#216] opened 2016-04-16 13:26 UTC
As reported https://wordpress.org/support/topic/great-seo-plugin-22?replies=1#post-8283912

**Comment by arnaudbroes** [comment] 2019-02-18 00:01
I'm not able to reproduce this. @wpsmort can you confirm this, label the issue as "can't reproduce" and close it if you can't either?

**Comment by EkoJR** [comment] 2019-02-18 04:47
@arnaudbroes I believe I may have already fixed this from another issue https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/292

**Comment by arnaudbroes** [comment] 2019-02-18 08:37
@EkoJR correct, thanks!

**Closed by arnaudbroes** 2019-02-18 08:37 UTC
Labels: Initial Review, Needs Reproducing
