### ISSUE TITLE
Change wording for notice

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1227] opened 2017-10-02 16:46 UTC
In #1225 we added a notice to change the settings.... now that we're forcing indexes and pagination, and making 1000 the default, we'll want to change the wording to reflect this (exclude things now being forced).

**Comment by wpsmort** [comment] 2019-03-14 13:57
Dupe of #1851

**Closed by wpsmort** 2019-03-14 13:57 UTC
