### ISSUE TITLE
illegal string offset warning in 2.3.6

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#379] opened 2016-07-04 22:16 UTC
Reported here: https://wordpress.org/support/topic/errors-on-save-1?replies=2#post-8602767

**Comment by michaeltorbert** [comment] 2016-07-04 23:47
I can't reproduce this, and I'm not sure why it's an issue to begin with by looking at the code.

**Comment by arnaudbroes** [comment] 2019-03-05 18:24
I'm not able to reproduce this either. I'm closing this issue since it's been so long since the initial report.

**Closed by arnaudbroes** 2019-03-05 18:24 UTC
Labels: Couldn't reproduce, Priority | Low
