### ISSUE TITLE
XML sitemap is not compatible to Google requirements

### ISSUE THREAD

**Issue by gvburg** [semperfiwebdesign/all-in-one-seo-pack#2344] opened 2019-04-24 03:51 UTC
This is not a support request, the XML file is a (for the Google Search Engine) broken feature. I have no other XML plugin active.

**Provide the relevant URL(s) here**
The website in question here: https://www.one-pm.com/
The generated XML file: https://www.one-pm.com/sitemap.xml
Google's internal analytical program: https://search.google.com/u/1/search-console/

**Describing the bug**
Google states themselves, they cannot read any URLs from your generated XML file, probably because generate URLs by their internal redirect instead of the full URL, e.g. "https://www.one-pm.com/en/one-wealth-en/" instead of your choice of putting "/en/one-wealth-en/" in the XML file.

**How to reproduce**
Your feature auto-generates the XML file, there is no special way to reproduce that. That's why this is no bug, this is a broken feature.

**Screenshots**
![image](https://user-images.githubusercontent.com/49916050/56631108-2c6ae600-6654-11e9-89c7-b033a5455105.png)

**Version Info (please complete the following information):**
 - WordPress version: 5.1.1
 - All in One SEO Pack version: 2.12
 - PHP version: 7.2.4

**Additional context**
You should probably add an opt-out option to have the full URLs of every page in the XML file. There should be the option to change, because it is unsure, if other search engines may be working better with a shortened version.

**Comment by michaeltorbert** [comment] 2019-04-24 05:34
Once again, you need to add steps to reproduce the issue. We can't do anything about special behavior on your website that can't be reproduced. 
You can find troubleshooting steps to narrow down a plugin or theme conflict here: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

As this issue in its current form is still not useful, I'm closing it too. It can be opened if/when you provide the necessary information.

**Closed by michaeltorbert** 2019-04-24 05:34 UTC

**Comment by gvburg** [comment] 2019-04-24 06:34
> You can find troubleshooting steps to narrow down a plugin or theme conflict here: https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

Unfortunately, I already stated that I disabled all plugins and went through troubleshoot. I am certain this is a bug or a broken feature.

> As this issue in its current form is still not useful, I'm closing it too. It can be opened if/when you provide the necessary information.

There is one way, and one way only to reproduce this bug: 1) install the plugin 2) do your settings as you wish, as I have attached the screenshot now. The XML has generated on it's own and has nothing to do with reproducable procedures.

As I now provided you with smth, you may either say what you need from me or open up the issue. If neither, then I assume you don't care enough.

**Comment by michaeltorbert** [comment] 2019-04-24 13:29
I care, it's simply that we can't do anything about that which we can't reproduce. Contrary to your claim, All in One SEO Pack uses absolute URLs. 

The single other time we've seen this, there was another plugin that was interferring and causing the URLs to change into relative URLs. The changed URLs being a symptom of an issue that had nothing to do with All in One SEO Pack.

As your comments on the two issues you've opened are both unproductive and abusive, I'm locking this issue and am blocking you from the repository.
