### ISSUE TITLE
Uploaded to this post dropdown (images) disappeared

### ISSUE THREAD

**Issue by netinial** [semperfiwebdesign/all-in-one-seo-pack#1899] opened 2018-09-11 08:54 UTC
After Auto Update (2.8)
Uploaded to this post (images) disappeared

Pages or Posts
Click Add Media
From Media Library
Under 
All Media Items
There should be Uploaded to this post.

I confirm that when I disabled AIOSEO from plugins it is appearing again.
False Screen
![adsiz](https://user-images.githubusercontent.com/1303482/45349155-36564200-b5b9-11e8-98ee-f3a892fffc85.jpg)

True Screen
![adsiz2](https://user-images.githubusercontent.com/1303482/45349218-60a7ff80-b5b9-11e8-913a-43f6b1149dac.jpg)

**Comment by michaeltorbert** [comment] 2018-09-11 13:16
@netinial We're unable to reproduce this, can you send us your wp-admin information so we can log in and resolve the issue? https://semperplugins.com/contact/support-login-information/

**Comment by netinial** [comment] 2018-09-11 14:12
I send via
https://semperplugins.com/contact/support-login-information/

**Comment by netinial** [comment] 2018-09-11 14:34
If there is no way. Ok.

**Comment by netinial** [comment] 2018-09-14 11:41
Dear Michael, This is almost 3 days and we still can not use our website to update pictures. (It shows all pictures instead of post's)

Since disabling is not good option.

Would you please let us know are there any update?

**Comment by michaeltorbert** [comment] 2018-09-14 11:46
@netinial When there are updates, you'll know on this page. Asking if there are any updates will only serve to slow development.

**Comment by michaeltorbert** [comment] 2018-09-15 00:44
When testing, we need to determine conclusively whether we introduced this in 2.8.

**Comment by contactashish13** [comment] 2018-09-15 07:01
That line of code (https://github.com/contactashish13/all-in-one-seo-pack/commit/968b1891e87e53e5f3cf4f2cc397d3ad94f08234#diff-604ad90165044b2b600ad4f4148dfacaL1771) seems to be there for the last 2 years so I doubt it was introduced in 2.8.

**Comment by michaeltorbert** [comment] 2018-09-15 18:35
I've confirmed that the bug does not exist in 2.7.3. @arnaudbroes Can you figure out which commit caused it?
Steps to reproduce:

Install AIOSEOP.
Install the active3 theme.
Create new post, add media, change tab to "media library," then "Uploaded to this post" is missing.

[active3.zip](https://github.com/semperfiwebdesign/all-in-one-seo-pack/files/2385990/active3.zip)

**Comment by netinial** [comment] 2018-09-15 20:47
Michael Is this private temporary clone ?
Please delete our theme from this place.

**Comment by wpsmort** [comment] 2018-10-18 14:04
This is resolved in the v2.9 release.

**Closed by wpsmort** 2018-10-18 14:04 UTC
Labels: Priority | High
