### ISSUE TITLE
sitemap 404 for compression

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1401] opened 2017-12-08 02:14 UTC
In some cases, the gz version of sitemaps results in a 404. We need to figure out the conditions.
Off the top of my head, I'd guess that index on and compression on causes the bug. We need to confirm, and then test to see when it started.

<img width="900" alt="screen shot 2017-12-07 at 9 13 27 pm" src="https://user-images.githubusercontent.com/17364998/33747895-87bc8d44-db93-11e7-8607-d782c059376e.png">
<img width="1021" alt="screen shot 2017-12-07 at 9 13 33 pm" src="https://user-images.githubusercontent.com/17364998/33747897-8961aad0-db93-11e7-8f02-b4e23ac07218.png">
<img width="986" alt="screen shot 2017-12-07 at 9 13 40 pm" src="https://user-images.githubusercontent.com/17364998/33747899-8ad129cc-db93-11e7-9e8a-d07b093932ce.png">

**Comment by arnaudbroes** [comment] 2017-12-08 20:44
@michaeltorbert I believe this is a duplicate of #1361

**Closed** 2017-12-11 21:37 UTC
Labels: Duplicate
