### ISSUE TITLE
Sitemap Priorities and Frequencies options don't work for main page

### ISSUE THREAD

**Issue by JakubPie** [semperfiwebdesign/all-in-one-seo-pack#2423] opened 2019-05-12 10:24 UTC
Sitemap: value change in Priorities and/or Frequencies for a main page does not reflect in sitemap.xml file - still shows "old" values.

**Comment by arnaudbroes** [comment] 2020-02-03 10:37
I'm not able to reproduce so I'll go ahead in close this without further investigation considering that we'll revisit priorities/frequencies at some point in the future.

**Closed by arnaudbroes** 2020-02-03 10:37 UTC
Labels: Needs Reproducing, User Reported
