### ISSUE TITLE
sitemap index and posts per page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1217] opened 2017-09-30 15:44 UTC
I suggest two things for considerations:

a) IF sitemap index is turned on, so should be the posts per page option (#1232)

b) posts per page should default to something low, like 1000

(these should be defaults, but we shouldn't change existing settings)

**Comment by wpsmort** [comment] 2017-09-30 16:55
@michaeltorbert I completely agree with these suggestions.

**Comment by wpsmort** [comment] 2017-09-30 17:13
@michaeltorbert I tested on a large site with another SEO plugin and found the same out of memory problem occurs when the pagination is set to 10,000.  Setting this to 1,000 that plugin or AIOSEOP worked fine.

Could we try to detect if either 1). an out of memory error is shown when the sitemap is built, or 2). if the site has more than 1,000 URLs, and return a red light and message that says "enable sitemap indexes"?

**Comment by michaeltorbert** [comment] 2017-09-30 17:19
@wpsmort 
1) maybe... we might be able to detect when we're about to run out of memory, but it wouldn't be 100% reliable
2) yes
3) we should also test all other SEO/sitemap plugins and see how much memory they use per x posts compared to us (only for ones with dynamic sitemaps)

**Comment by wpsmort** [comment] 2019-03-14 13:59
Dupe of #1929

**Closed by wpsmort** 2019-03-14 13:59 UTC
Labels: In Development
