### ISSUE TITLE
Double quotes not escape in meta descriptions

### ISSUE THREAD

**Issue by fahmi182** [semperfiwebdesign/all-in-one-seo-pack#928] opened 2017-06-04 11:42 UTC
Hi, i'm your member aio PRO, our problem is, double quotes in meta description not escape, that cause error our html format, can you check please?

Thanks!

**Comment by wpsmort** [comment] 2017-06-04 17:43
Reported here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/meta-descriptions-double-quotes-not-escape/#p6643

**Comment by wpsmort** [comment] 2017-06-06 16:34
Duplicate of #593

**Closed by wpsmort** 2017-06-06 16:34 UTC
Labels: Initial Review, Priority | Medium
