### ISSUE TITLE
AIOSEOP blocks ul class=”woocommerce-error”

### ISSUE THREAD

**Issue by SimbaAowhoo** [semperfiwebdesign/all-in-one-seo-pack#1747] opened 2018-06-21 14:21 UTC
**Describe the bug**
When AIOSEOP is enabled, the error messages such as "Invalid username", "The password you entered is incorrect." are not displayed on /my-account/ page. ul class=”woocommerce-error” is not produced when AIOSEOP is enabled.

**To Reproduce**
1. Go to /my-acccount/
2. Click sign in without typing username or click sign in with wrong/empty passwords

**Expected behavior**
Error messages such as "Invalid username", "The password you entered is incorrect." inside ul class="woocommerce-error" should be displayed.

**Version Info (please complete the following information):**
 - WordPress version: 4.9.6
 - WooCommerce version: 3.4.2
 - All in One SEO Pack version: 2.6.1
 - PHP version: 7.2
 - Storefront Theme Version: 2.3.2
 - Twenty Seventeen Theme

**Additional context**
I didn't think AIOSEOP would do this to login form but the result was from testing every single plugin out of 50+ plugins that I have.

**Comment by michaeltorbert** [comment] 2018-06-22 14:46
Reported again by Rama via email:

> I found the meta description added by the SEO Pro somehow interfering with the woocommerce error message.

**Comment by michaeltorbert** [comment] 2018-06-22 14:47
After verifying the issue, see if a recent update to either https://github.com/woocommerce/woocommerce or AIOSEOP caused this.

**Comment by michaeltorbert** [comment] 2018-07-02 14:10
Reported again by https://wordpress.org/support/topic/woocommerce-login-errors-missing/#post-10454848

**Comment by arnaudbroes** [comment] 2018-07-14 10:43
I'm not able to reproduce this using the exact same environment as @SimbaAowhoo. The error messages are showing up on my site. There might be a configuration issue.

@SimbaAowhoo, would you willing to give me access to your website so I can duplicate it and continue troubleshooting the issue? If so, please use our secure form to send us the credentials for an administrator user - https://semperplugins.com/contact/submit-login-information/. We won't make any changes to your live site, and any submitted data and the clone of your website will be deleted as soon as we've finished troubleshooting the issue.

In the meanwhile, I'll ask @wpsmort to see if he can reproduce this.

**Comment by arnaudbroes** [comment] 2018-07-19 12:58
I've tracked this issue down to our "Run shortcodes in the description" setting at the bottom of the Social Meta menu which is known to cause similar issues with other plugins that also use shortcodes. 
Disabling it resolves this issue.

**Comment by michaeltorbert** [comment] 2018-07-19 19:00
@arnaudbroes Make a note for us to discuss this with Steve.
As for this issue, we should probably look into some better way to handle it since it keeps coming up, for WC at least.

**Comment by wpsmort** [comment] 2019-01-09 16:30
Reported again by sam by email today.

**Comment by wpsmort** [comment] 2019-01-10 23:52
@arnaudbroes Were you able to track down which version and which commit broke this?  If not, can you do this so we can better understand what changed caused this conflict.

**Comment by arnaudbroes** [comment] 2019-01-13 16:48
@wpsmort I tracked this down to 2.2.3, which is when the "Run shortcodes in the description" was introduced, which means that it never worked.

**Comment by wpsmort** [comment] 2019-01-17 19:53
Thanks @arnaudbroes. I'll leave this assigned to you as the owner.  I'll remove the high priority as this has been a problem for a long time.

**Comment by contactashish13** [comment] 2019-05-23 08:19
@arnaudbroes I believe this can be closed in preference to #1846

**Comment by michaeltorbert** [comment] 2019-05-23 11:46
@contactashish13 We aren't necessarily removing that option yet, so this can't be closed.

**Closed** 2019-05-30 22:23 UTC
Labels: Conflict, Has been reproduced, User Reported
