### ISSUE TITLE
We have detected you are running WooCommerce. Upgrade to All in One SEO Pack Pro to unlock our advanced e-commerce features, including SEO for Product Categories and more.

### ISSUE THREAD

**Issue by Justabandit** [semperfiwebdesign/all-in-one-seo-pack#2579] opened 2019-06-05 19:17 UTC
Since last update this notification will not go away. Get rid of it

"We have detected you are running WooCommerce. Upgrade to All in One SEO Pack Pro to unlock our advanced e-commerce features, including SEO for Product Categories and more."

**Comment by michaeltorbert** [comment] 2019-06-05 19:17
Duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2556

**Closed by michaeltorbert** 2019-06-05 19:17 UTC
