### ISSUE TITLE
Bug - Robots meta tag doesn't have correct closing tag

### ISSUE THREAD

**Issue by Babene03** [semperfiwebdesign/all-in-one-seo-pack#2876] opened 2019-09-06 18:17 UTC
In the Sourcecode of the Site, is no END Tag **>** from the Meta Tag

`<meta name="robots" content="noindex,nofollow"`

**Comment by michaeltorbert** [comment] 2019-09-06 18:41
I'm unable to reproduce this behavior, which means it's likely a problem specific to your site. Please use these troubleshooting steps to narrow down a plugin/theme conflict. https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack/

If you're able to reproduce it on your site with all plugins other than AIOSEOP active, and with the unmodified default theme active, then please post the link to your site.

**Comment by michaeltorbert** [comment] 2019-09-06 18:50
Thank you for reporting this. I've been able to reproduce this and have verified it is a bug.
I've assigned it to be fixed for the next major release.

**Comment by michaeltorbert** [comment] 2019-09-06 18:51
@Babene03 
Thank you for reporting this. I've been able to reproduce this and have verified it is a bug.
I've assigned it to be fixed for the next major release.

**Comment by michaeltorbert** [comment] 2019-09-06 18:53
The problem is on https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/8b5b6a6960af511fdd786d5a42b8d768044b05dd/aioseop_class.php#L4219

Also, and this should probably be its own issue, we seem to be doing robots meta in two places. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/8b5b6a6960af511fdd786d5a42b8d768044b05dd/aioseop_class.php#L4341
We should probably look into improving that.

**Comment by michaeltorbert** [comment] 2019-09-06 18:58
As this was broken in 3.2.2, we should include it in 3.2.6.

**Comment by Babene03** [comment] 2019-09-06 19:07
I think the issue is

`printf( "<meta name=\"robots\" content=\"%s\" >\n", esc_attr( $robots_meta ) );`

**Comment by michaeltorbert** [comment] 2019-09-06 19:09
@Babene03 Correct, which is also what I've posted above. ;)

**Closed** 2019-09-08 21:22 UTC
Labels: Has PR, Has been reproduced, Priority | Medium, User Reported
