### ISSUE TITLE
WC-Marketplace doesn't publish when AIOSEOP is active

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1837] opened 2018-08-13 14:46 UTC
Reported here: https://wordpress.org/support/topic/problem-for-multivendor/

**Comment by arnaudbroes** [comment] 2018-09-08 18:42
I tested this but couldn't reproduce the problem. This works as expected. Could be a configuration issue. I'll close this for now, but I'll inform the user and he can reopen the issue if needed.

![image](https://user-images.githubusercontent.com/18156697/45257486-675f2880-b3a7-11e8-9174-cead0eaa6aa2.png)

**Closed by arnaudbroes** 2018-09-08 18:42 UTC
Labels: Couldn't reproduce
