### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OB1212** [semperfiwebdesign/all-in-one-seo-pack#2332] opened 2019-04-12 03:30 UTC
Hi, your Plugin gives me an Log-Error: 

[12-Apr-2019 03:07:38 UTC] PHP Notice:  Trying to get property of non-object in /www/htdocs/xxxxxxx/xxxxx/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 1623

Please fix it and give an Update for This Plugin , or tell me what can i do now??

**Comment by wpsmort** [comment] 2019-04-12 16:13
Dupe of #1616

**Closed by wpsmort** 2019-04-12 16:13 UTC
