### ISSUE TITLE
ALL IN OBE SEO PACK : Issues with google indexing : blocked by robots.txt

### ISSUE THREAD

**Issue by liberofusi** [semperfiwebdesign/all-in-one-seo-pack#2801] opened 2019-08-08 07:58 UTC
I'm a SEO specialist that generated tens of sites specially developed for SEO
This is the first time I had such a issue

**Describe the bug**
GSC:
Submission of the sitemap generated by ALL IN ONE SEO PACK generates "Sitemap could not be read"
URL control of a generic page generates "Indexed, though blocked by robots.txt"

The google command : site:e-learning.mkt-knowledge.com generates a lot of pages without metatitles and metadescriptions
The initial issue is that the sitemap has the **x-robots-tag: noindex, follow**
Why? It's generated by ALL IN ONE SEO PACK

This is the robots.txt (generated by ALL IN ONE SEO PACK):
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
Sitemap: https://e-learning.mkt-knowledge.com/sitemap.xml

**To Reproduce**
GSC for submission
Google command site:e-learning.mkt-knowledge.com

**Expected behavior**
I espect the normal Google site indexing : some hundreds pages indexed with metatitle adn metadescriptions

**Screenshots**
See screenshots

**Version Info (please complete the following information):**
 - WordPress version: 5.2.2
 - All in One SEO Pack version:3.2.2
 - PHP version: 7.1.30

**Additional context**
SIte is hosted by Siteground

![gsc1](https://user-images.githubusercontent.com/53893941/62685414-e77c7c80-b9c2-11e9-8c33-6df73c7b0b69.JPG)
![site2](https://user-images.githubusercontent.com/53893941/62685415-e77c7c80-b9c2-11e9-92cb-ee8ec3da6e56.JPG)
![site1](https://user-images.githubusercontent.com/53893941/62685418-e77c7c80-b9c2-11e9-80bc-53d951d348bf.JPG)
![gsc3](https://user-images.githubusercontent.com/53893941/62685420-e77c7c80-b9c2-11e9-8001-1959dba87793.JPG)
![gsc2](https://user-images.githubusercontent.com/53893941/62685423-e8151300-b9c2-11e9-8746-67949d711a03.JPG)

![header2](https://user-images.githubusercontent.com/53893941/62687569-522fb700-b9c7-11e9-9a38-dc46a43e7657.JPG)

**Comment by michaeltorbert** [comment] 2019-08-08 12:38
Noindex, follow is correct to include in the headers for the sitemap.
Google is saying that the robots.txt has (or an earlier version had) a directive blocking Google.

My guess is that during development, you chose the WP option to block search engines from crawling your website, and that was cached.
Deleting your site from GSC and re-adding it may fix the issue. 

As this is a support problem, and not a bug, I'm closing the issue.

**Closed by michaeltorbert** 2019-08-08 12:38 UTC
