### ISSUE TITLE
Not able to Fetch as Google

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1261] opened 2017-10-04 11:10 UTC
Reported here: https://wordpress.org/support/topic/google-webmaster-sitemap-error/#post-9554319 and via email from Jivan.

> * Not able to Fetch as Google post urls .
Error Type
Temporarily unreachable

But home page url successfully Fetched.

**Comment by bimal008** [comment] 2017-10-04 15:28
HI guys ,
This is really a serious matter of concern, since googlebot can't Crawl sites post pages this will indicate a negative impact to its SEO, i believe.

Furthermore, I refer this thread & my last reply in it, for better understanding https://wordpress.org/support/topic/google-webmaster-sitemap-error/#post-9556018

Also i wanted to ask you, when you are going to release then next updated version of it with the *Fix of this issue.

Best Regards

**Comment by michaeltorbert** [comment] 2017-10-04 15:30
@bimal008 Pease stop the constant messages. As you can see, we are working on it.

**Comment by wpsmort** [comment] 2019-03-20 22:01
I don't have the steps to reproduce this, however, the Parsing error reported by the user is most likely an issue with a special character that we weren't encoding properly.  We've had many reports of this over the years with different special characters and have made improvements to the XML Sitemap module that should now encode all special characters correctly.

The other error reported was Temporarily unreachable which, as the error indicates, is usually a temporary issue which could be caused by a site outage, server problem or any other problem that prevents Google from fetching that URL at that moment.  These usually clear up on there own when Google retries.

I am closing this issue as we don't know what the specific cause of the parsing error was.  I've not had any issues with Google fetching the posts sitemap for my various public sites.

**Closed by wpsmort** 2019-03-20 22:01 UTC
Labels: Initial Review, Needs Reproducing, Priority | Medium, User Reported
