### ISSUE TITLE
meta description hook isn't always overriding

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#958] opened 2017-07-13 18:59 UTC
The aioseop_description filter hook should be the last thing that runs for the meta description; it should override everything else.

We had %description% - %cf_short_description% as the description template, and using the filter hook as:

add_filter( 'aioseop_description', 'change_description', 10, 2 );

function change_description( $desc ){
	
	if( ! is_singular( 'movies' ) ){
		return $desc;
	}
	
	$acf_desc = 'my acf desc';
	
	return "$desc $acf_desc";
}

It returns with:
[meta description field for that post] ]$acf_desc $acf_desc [cf_short_description]

**Comment by wpsmort** [comment] 2017-07-13 19:00
We need to see if this is new in the last few versions. We made some changes to the aioseop_description filter hook in 2.3.13.

**Comment by michaeltorbert** [comment] 2017-07-13 19:21
This means the filter gets applied twice...

**Comment by michaeltorbert** [comment] 2017-07-13 20:22
This is a probable dupe of #932

**Closed** 2017-07-13 21:08 UTC
