### ISSUE TITLE
Title and meta description aren't getting saved on *some* pages

### ISSUE THREAD

**Issue by lizsterine** [semperfiwebdesign/all-in-one-seo-pack#1084] opened 2017-08-14 05:32 UTC
This problem is occurring on two sites that use the All in one SEO pack v2.3.15.3 on WordPress v4.8

There are a few existing pages that are unable to have the metadata titles and descriptions updated using the SEO pack plugin interface.

This appears to be with pages that have been saved previously however the problem appears to be isolated to a few pages while others are fine.

I've done the usual debugging of deactivating all other plugins and swapping to a plain Wordpress theme and the results are still the same.  

I've looked in the database and can find no obvious reason why this would be the case. Can you please help by providing some guidance and direction to solve this issue?

Thanks very much!

**Comment by wpsmort** [comment] 2017-08-14 19:51
Are you able to reproduce this on a test site with no other plugins active and with the default Twenty Seventeen theme active?  I am unable to reproduce this at all on a plain site or an existing site and no other user has reported this problem.  

If you are able to reproduce this on a plain site then please send us the WordPress administrator login and we'll troubleshoot it.  You can send login information using the secure form at - https://semperplugins.com/contact/submit-login-information/

**Comment by michaeltorbert** [comment] 2017-08-15 21:07
@lizsterine Unfortunately there's nothing we can do unless you're able to help us reproduce the issue.

**Comment by arnaudbroes** [comment] 2017-08-17 16:34
I'm not able to reproduce this either.

**Comment by michaeltorbert** [comment] 2017-08-17 16:38
Closing until this can be confirmed with steps to reproduce or login info.

**Closed by michaeltorbert** 2017-08-17 16:38 UTC
