### ISSUE TITLE
Redesign user interface.. tabs?

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#198] opened 2016-04-15 21:03 UTC
Divide user interface into tabs?

**Comment by nishant981** [comment] 2016-04-27 10:15
Can you please send the screenshot for the user interface tabs.

**Comment by michaeltorbert** [comment] 2016-05-06 23:21
https://premium.wpmudev.org/blog/tabbed-interface/

**Comment by michaeltorbert** [comment] 2017-01-18 01:42
Duplicate of #127

**Closed** 2017-01-18 01:42 UTC
Labels: Design, Duplicate, Optimization
