### ISSUE TITLE
Bug with video sitemap when added to XML Sitemap indexes 

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1650] opened 2018-04-10 22:17 UTC
Reported here - https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/sitemap-errors-1/

When a site is running the XML Sitemap module with sitemap indexes enabled and they activate the Video Sitemap module but don't save anything then the video sitemap is added to the main XML sitemap as:

http://domain.com/.xml

It should show up as:

http://domain.com/video-sitemap.xml

To reproduce this bug follow these steps:

1. Install AIOSEOP Pro on a new site
2. Activate the XML Sitemap module and Video XML Sitemap module
3. Go to the Sitemap module and enable Sitemap Indexes and click Update Options
4. View the XML Sitemap and you should see the last sitemap entry is http://domain.com/.xml.gz

**Comment by arnaudbroes** [comment] 2018-04-11 13:51
@wpsmort  I checked this and this bug was introduced with 2.5 when we decided to include the Video XML Sitemap URL in the regular sitemap.xml.

**Comment by contactashish13** [comment] 2018-11-08 06:49
@arnaudbroes I think this was introduced much later in 2.7.1. as part of the fix for https://github.com/semperfiwebdesign/aioseop-pro/issues/412. Can you please confirm?

@wpsmort I believe this issue is related to https://github.com/semperfiwebdesign/aioseop-pro/issues/424 and is fixed by #1887.

**Comment by arnaudbroes** [comment] 2018-11-20 10:40
@contactashish13 I reconfirmed that this issue was introduced in v2.5. However, you're correct that the issue is no longer present.

**Comment by wpsmort** [comment] 2018-12-06 18:01
Reopening this as it is not fixed and is still present.

**Comment by contactashish13** [comment] 2018-12-07 05:39
@wpsmort PRs: https://github.com/semperfiwebdesign/aioseop-pro/pull/459 and https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2101

**Closed** 2018-12-31 18:35 UTC
Labels: Bug, Priority | High
