### ISSUE TITLE
problem with site map

### ISSUE THREAD

**Issue by HOTDOG2705** [semperfiwebdesign/all-in-one-seo-pack#2018] opened 2018-10-26 18:45 UTC
Hello, I have problem with the site map, suddenly after the last upgrade stopped working! Google doesn't recognize it anymore and clicking on show sitemap gives back an empty page. 

Edit..
Sorry just saw that there is another thread on the same topic open... you can close this one I think. Thanks

**Comment by wpsmort** [comment] 2018-10-26 19:58
Dupe of #2014

**Closed by wpsmort** 2018-10-26 19:58 UTC
