### ISSUE TITLE
XML sitemap - "additional pages" add URL button needs CSS fix

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1128] opened 2017-09-05 23:04 UTC
![image](https://user-images.githubusercontent.com/18156697/30087157-4d880f0a-929f-11e7-96f3-57c271b7ed7f.png)

**Comment by wpsmort** [comment] 2017-09-06 20:01
Duplicate of #802

**Closed by wpsmort** 2017-09-06 20:01 UTC
