### ISSUE TITLE
"All in One SEO" instead of "All in One SEO Pack" in XML sitemap

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2198] opened 2019-02-14 10:08 UTC
This should be All in One SEO Pack imo.

![image](https://user-images.githubusercontent.com/18156697/52779563-bbea8c00-3048-11e9-8f08-101129325de7.png)

**Comment by michaeltorbert** [comment] 2019-02-26 17:29
dupe of #1972

**Closed by michaeltorbert** 2019-02-26 17:29 UTC
Labels: Duplicate
