### ISSUE TITLE
Schema.org - Add support for Product

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2924] opened 2019-09-19 12:28 UTC
Requested by Dorte R. on 09/18.

We'll need to discuss whether this is something we should do or if this is something better suited for dedicated Schema.org plugins or eCommerce plugins.

**Comment by wpsmort** [comment] 2019-11-22 21:48
Closing as a dupe of https://github.com/semperfiwebdesign/aioseop-pro/issues/98

**Closed by wpsmort** 2019-11-22 21:48 UTC
Labels: Enhancement, Initial Review
