### ISSUE TITLE
fix layout on feature manager screen

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#327] opened 2016-06-12 21:34 UTC
Somehow we seem to have broken this in dev? 

changes: https://github.com/semperfiwebdesign/all-in-one-seo-pack/commits/development/css/modules/aioseop_module.css

<img width="1440" alt="screen shot 2016-06-12 at 5 31 48 pm" src="https://cloud.githubusercontent.com/assets/17364998/15993954/b343c6ca-30c3-11e6-9b3c-18f48eedc9e5.png">

**Comment by wpsmort** [comment] 2016-06-13 13:18
This was caused by the CSS fix for the message that appears when you activate/deactivate a module.  I have committed a minor CSS fix for this.

**Closed by wpsmort** 2016-06-13 13:18 UTC
