### ISSUE TITLE
Problem with PageSpeed Ninja plugin - erasing "title" from page

### ISSUE THREAD

**Issue by RomanKashtanov** [semperfiwebdesign/all-in-one-seo-pack#2102] opened 2018-12-07 14:26 UTC
Please test your plugin with PageSpeed Ninja because working together these plugins makes global problem for SEO for Title - it starts using the site name, which is not in All in One SEO, but is in the general settings of the site

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:

**Additional context**

**Comment by wpsmort** [comment] 2018-12-07 14:57
@RomanKashtanov Are you referring to this plugin - https://wordpress.org/plugins/psn-pagespeed-ninja/

Please provide exact details on how to reproduce the problem you are seeing.  If you can provide us with a login for a site where this issue can be seen then please send that to us using the secure form here - https://semperplugins.com/contact/support-login-information/

**Comment by michaeltorbert** [comment] 2018-12-07 20:24
@RomanKashtanov I've edited your post to add in the bug report template which you should have used. At the moment, you haven't given us enough information to go on.

**Comment by arnaudbroes** [comment] 2018-12-15 15:42
I'm not able to reproduce this nor have we received more information so I'm closing this until @RomanKashtanov provides more information.

**Closed by arnaudbroes** 2018-12-15 15:42 UTC
Labels: Couldn't reproduce
