### ISSUE TITLE
Raise memory limit doesn't work on some servers

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#638] opened 2016-10-31 16:47 UTC
Whilst looking at the new http://yakmybody.com/ site on Cloudways, we saw that the memory limit reported in Performance > System Status did not match what was selected in the Raise memory limit setting.  

Upon testing the config for the server, I raised the memory for the server to 256M and then to 512M and both times we reflected the correct memory.  

Changing the memory allocated to PHP under the website settings in Cloudways (Application Settings > PHP Settings) was not reflected in our system status. Neither BackupBuddy, Query Monitor or WooCommerce could accurately reflect this either, they all showed the same as AIOSEOP which was the memory set at the server level.

**Comment by EkoJr** [comment] 2018-02-04 21:02
I noticed this issue as well when installing WPML. In this case WPML displays 2 different memory constants, which seems to have 1 excluded.

With WPML installed. Go to WPML > Support...
![wpml-support-memory-info](https://user-images.githubusercontent.com/2794445/35782366-9917a56a-09ab-11e8-8144-519164e70204.png)

https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP

**Comment by michaeltorbert** [comment] 2019-03-13 18:28
@arnaudbroes Here we are 2.5 years. See if any of those plugins are doing things better. Otherwise, we just may not be able to change this on some servers and this issue should be closed.

**Comment by arnaudbroes** [comment] 2019-06-24 14:24
I'm not able to reproduce this in a local environment (nginx and apache) and on CW (nginx), so I'll just go ahead and close this. AIOSEOP is reporting the same value as WooCommerce in each test case.

**Closed by arnaudbroes** 2019-06-24 14:24 UTC
