### ISSUE TITLE
Plugin Disables DIVI theme options

### ISSUE THREAD

**Issue by elena-novinskiy** [semperfiwebdesign/all-in-one-seo-pack#1259] opened 2017-10-03 22:14 UTC
Hi there,

I am using DIVI theme for my website. I updated to the latest version of all-in-one-seo pro and DIVI theme options are no longer showing. Disabling the plugin puts everything back to normal. Please, let me know if this can be somehow resolved.

Thank you!
Elena.

**Comment by michaeltorbert** [comment] 2017-10-03 22:15
Closing as a duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1251

**Closed by michaeltorbert** 2017-10-03 22:15 UTC
Labels: Duplicate
