### ISSUE TITLE
Pipe is added to post/page doc title even if it's not in the template

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#645] opened 2016-11-03 19:14 UTC
Reported here: https://wordpress.org/support/topic/remove-pipe-or-dash-in-page-title/

**Comment by michaeltorbert** [comment] 2017-02-27 22:03
I can't reproduce this.

**Comment by wpsmort** [comment] 2017-03-02 22:13
@michaeltorbert: I can't reproduce this.  I also see that a site search of that site shows that Google is now showing the title in SERPS as:

Top 27 SSIS Interview Questions - Career Guru99

The source code of that post has a title tag of:

Top 27 SSIS Interview Questions |

However, as the comment line has been removed we can't see if the obstart -1-1 message is being displayed to indicate that something else is interfering with our title output.

We need access to the site in order to troubleshoot further.

**Comment by wpsmort** [comment] 2017-03-02 23:27
I've tried to reproduce this with v2.3.11 and v.2.3.11.1 and cannot reproduce it.  It may be a conflict with the Enfold theme so we should watch for any reports of this again.

**Comment by arnaudbroes** [comment] 2019-02-18 00:53
I'm not able to reproduce this either so I'll go ahead and close this issuse. Steve is probably right about this being a theme issue.

**Closed by arnaudbroes** 2019-02-18 00:53 UTC
Labels: Bug, Initial Review

**Comment by michaeltorbert** [comment] 2019-02-18 15:47
This is something that's been reported numerous times, but we've never been able to reproduce it.
