### ISSUE TITLE
Autogenerate Descriptions: Problem

### ISSUE THREAD

**Issue by mobilapk** [semperfiwebdesign/all-in-one-seo-pack#1308] opened 2017-10-15 17:29 UTC
Everyone Merhabalar

I have been using all in seo for a long time. I noticed a problem today. The "Autogenerate Descriptions" feature is turned on in the settings;

![image](https://user-images.githubusercontent.com/29548030/31587253-2dc93f60-b1e7-11e7-91f9-c1a749158226.png)

But this feature works on some pages.

![image](https://user-images.githubusercontent.com/29548030/31587274-764c040c-b1e7-11e7-85dd-0625bed2e920.png)

some pages do not work.

![image](https://user-images.githubusercontent.com/29548030/31587277-88fb3f1e-b1e7-11e7-9fb3-ac6292e9e297.png)

This plugin needs to be updated.

**Comment by michaeltorbert** [comment] 2017-10-15 17:39
Please provide steps to reproduce the issue.

**Comment by mobilapk** [comment] 2017-10-16 05:55
Which steps I will follow. The problem is already present.

**Comment by arnaudbroes** [comment] 2017-10-16 13:04
@mobilapk 
We need you to provide us with the exact steps to reproduce this issue.
We can't fix something that we aren't able to reproduce.

**Comment by mobilapk** [comment] 2017-10-17 18:24
I did nothing to create the problem. I have not changed for years, I noticed it a week ago.

**Comment by michaeltorbert** [comment] 2017-10-17 20:14
@mobilapk We have been unable to reproduce this issue. So that we can investigate further, you can submit your username and password to our secure form here: https://semperplugins.com/contact/submit-login-information/

**Comment by mobilapk** [comment] 2017-10-18 10:02
I sent the form and sent it. I added the bug address to the description.

**Comment by mobilapk** [comment] 2017-10-19 18:28
Any progress ?

**Comment by michaeltorbert** [comment] 2017-10-20 04:30
When an image is in the content, it breaks our scanning for the meta description.


_content part 1
<img src="http://someurl.com/someimage.jpg" /> 
content part 2_
results in meta description = "content part 1"

Interestingly, 
_content part 1
<img src="http://someurl.com/someimage.jpg" /> 
content part 2
<img src="http://someurl.com/someimage.jpg" /> 
content part 3
_
results in meta description = "content part 1 content part 3"

**Comment by mobilapk** [comment] 2017-10-20 05:35
is this a plug-in bug?

**Comment by contactashish13** [comment] 2017-10-20 07:23
@michaeltorbert one potential problem appears to be https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L4916 where, i'm not sure why, the tags are being cleared only for php v5.2.  This conditions has been introduced in 2.3.14.1 with this commit: https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/ad495008424f99a5343971044bcb057b9eb1aeb2#diff-4e533641bc4be27bca19bde1a2b60fe9

I cannot find a reason for adding this condition. If that version check is removed, it will correctly remove all tags. 

2. https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L4922 does not make much sense because wp_strip_all_tags will anyways do this.

**Comment by michaeltorbert** [comment] 2017-10-20 18:18
I'm not sure, it was added for this issue: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/933

**Comment by contactashish13** [comment] 2017-10-22 06:32
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1322

Even though I've tried to be careful to not tread on any of the previous changes, I feel this needs a fair bit of testing.

@wpsmort could you mention the kind of text that got removed when you were testing #932 for which changes were made in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/933? It will help me generate the test case for that condition.

**Comment by arnaudbroes** [comment] 2017-10-22 13:57
@contactashish13 best to ask questions for @wpsmort to me or Michael since he has broken his back and is unavailable for the time being. I'll check this and get back to you.

**Comment by mobilapk** [comment] 2017-10-22 15:51
Yes, how do I solve this problem?

**Comment by arnaudbroes** [comment] 2017-10-22 16:11
@mobilapk We are working on it.

**Comment by mobilapk** [comment] 2017-10-22 21:15
@arnaudbroes thank you. I expect to be resolved

**Comment by michaeltorbert** [comment] 2017-10-23 01:26
I've deleted the extraneous comments. 

This is a development repository site, not a place for chit chat, or for user support. We do not provide release dates. Constantly asking questions and making these types of comments would only delay a release.

**Comment by wpsmort** [comment] 2018-03-20 22:04
Note: The bug reported here where autogenerated descriptions break when an image is present was fixed by #1402 in v2.4.4

**Comment by wpsmort** [comment] 2018-03-20 22:35
@contactashish13  There is still a bug here.  

I found that with the current version of AIOSEOP v2.4.6.1 and the code in your PR #1322, the auto generated meta description is not displayed in the Description field when an HTML special character appears in the excerpt or content and PHP 5.2 in running.

To reproduce this, add a special character such as &nbsp; or &copy; in your excerpt or content where it will be picked up as part of the auto generated description.

<img width="874" alt="screen shot 2018-03-20 at 6 34 10 pm" src="https://user-images.githubusercontent.com/17548525/37686317-4da16456-2c6d-11e8-9b5a-4438ae01ccd8.png">

**Closed** 2018-08-29 02:27 UTC
Labels: Bug
