### ISSUE TITLE
Bad Bot Blocker - Bad bot list is getting applied to both user agents and referrers

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#481] opened 2016-09-08 18:43 UTC
The bad bot list is getting applied to both user agents to block and referrers to block.

It could either be a) our update script that did it or b) AIOSEOP core does it.

**Comment by michaeltorbert** [comment] 2016-10-10 01:55
This happens only when using the custom (unedited) lists + htaccess.

We need to determine what version started this.

**Comment by michaeltorbert** [comment] 2016-10-10 02:40
I went all the way back to 2.2.7 (when the Bad Bot module was introduced) and it was doing this. As this is not a new issue, I'm sending it to 2.3.11.

**Comment by michaeltorbert** [comment] 2016-10-10 02:46
This may be a duplicate of #439?

**Comment by michaeltorbert** [comment] 2016-10-10 02:46
@wpsmort This may be a duplicate of #439?

**Comment by michaeltorbert** [comment] 2016-11-14 22:07
Since we're removing htaccess functionality in #657 and #653, we should close this.
First test that it's only htaccess and not ever what's stored in the options for custom. Verify that you can reproduce the bug for htaccess AND that it ONLY affects htaccess and not HTTP (look at the database).

**Closed** 2017-01-19 21:31 UTC
Labels: Bug
