### ISSUE TITLE
Schema.org - Corporate contact markup for Google Knowledge Panels is deprecated

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#3032] opened 2019-11-13 18:02 UTC
FYI: 

> Corporate Contact markup for Google knowledge panels is deprecated. We now automatically discover corporate contact information to include in Google knowledge panels.

https://developers.google.com/search/docs/data-types/corporate-contact

_Originally posted by @Garconis in https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/509#issuecomment-553467866_

**Comment by wpsmort** [comment] 2019-11-19 22:59
Dupe of #2694.  

We need to retain the markup as Bing may be using it.

**Closed by wpsmort** 2019-11-19 22:59 UTC
Labels: Initial Review
