### ISSUE TITLE
XML Sitemap - AMP support for sitemaps

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#385] opened 2016-07-06 20:38 UTC

**Comment by michaeltorbert** [comment] 2016-07-22 02:41
https://support.google.com/webmasters/answer/6340290?hl=en
http://technicalseo.com/seo-tools/amp/

**Comment by wpsmort** [comment] 2016-09-16 21:05
This is a duplicate of #37.  Merging these issues.

**Closed by wpsmort** 2016-09-16 21:05 UTC
Labels: Feature, Initial Review
