### ISSUE TITLE
apply_post_title_format() sometimes called on page/custom post type

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2142] opened 2019-01-13 17:35 UTC
Reported by @harryrobbins #2137. 

> "Sometimes (for reasons which are not clear to me) apply_post_title_format() is called on a page or custom post type. This currently causes the title in the of the page to be printed as the format (e.g. <title>%page_title% | %blog_title%</title>) instead of the parsed template.

**Comment by arnaudbroes** [comment] 2019-01-17 20:17
Here's some more info from Harry.

> "I've done a bit more digging and I think I've found the issue.
> 
> Your plugin uses the "is_page()" to determine which title function to use.
> e.g on e.g. aioseop.class.php line 1656
> 
> The "is_page" function relies on the WP_Query::is_page property which is
> sometimes set to false even if the underlying post type is a page (due to
> various things such as the "show_on_front" variable).
> 
> This results in a page post-type making it all the way through the various
> If statements in get_aioseop_title and getting to Line 1732 where "
> apply_post_title_format" is called.
> 
> I believe the issue is that is_page() is intended for determining which
> template to use, rather than which post type to query."

**Comment by arnaudbroes** [comment] 2019-01-17 20:19
@EkoJR can you have a look and see if you're able to reproduce and/or whether Harry's information makes sense to you from a code perspective.

**Comment by EkoJR** [comment] 2019-01-18 06:42
There's 2 functions that achieve similar results. 

`apply_page_title_format()` & `apply_post_title_format()`

It seems he's trying to replicate the page function on a post. Which would be resolved by using %post_title% instead, but seems to alternate between the two. I don't think I would be able to reproduce this without more info about the website; since I suspect another plugin played a part (either part of its modifications, or post was converted to a page).

I believe it just needs to check if the post is in a hierarchical post type, and then use 1 of the 2 functions listed above.

I also think it would help if the plugin would drop %page_title% in favor of just %post_title%; as well as reduce any other %page_&ast;% in favor of %post_&ast;% shortcodes. Both likely operate the same already, and it would reduce code, bugs like this, and confusion.

**Comment by arnaudbroes** [comment] 2019-01-25 14:01
@harryrobbins are you able to provide us with steps to reproduce this problem, or alternatively, give us access to your website so we can take a look?

**Comment by michaeltorbert** [comment] 2019-02-20 22:43
Closing this as nobody has been able to reproduce it.

**Closed by michaeltorbert** 2019-02-20 22:43 UTC
Labels: Bug, Initial Review, Needs Reproducing
