### ISSUE TITLE
PHP Notices: Trying to get property of non-object

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1545] opened 2018-02-05 15:15 UTC
Reported here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/erorr/

PHP Notice: Trying to get property of non-object in /wp-content/plugins/all-in-one-seo-pack-pro/admin/aioseop_module_class.php on line 2864

PHP Notice: Trying to get property of non-object in /wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php on line 1137

PHP Notice: Trying to get property of non-object in /wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php on line 1146

**Comment by michaeltorbert** [comment] 2018-02-05 17:17
FYI

`$term_id = $term_id ? $term_id : get_queried_object()->term_id;`
`$term_id = $term_id ? $term_id : get_queried_object()->term_id;`
`$description = get_queried_object()->description;`

**Comment by EkoJr** [comment] 2018-02-25 10:39
I added some changes that I believe would resolve the issue, but I was unable to reproduce the error.

I ran different tests with different PHP versions, but neither cause the issue to trigger. I suspect either the issue relates to a nested function `get_terms()` where some recent changes have taken place...or...I suspect a 3rd party conflict possibly in `get_terms()` or `get_terms_by()`, or the object itself being return.

It's difficult to say what exactly is taking place, but added a commit anyways that may better handle the return.

**Comment by michaeltorbert** [comment] 2018-02-25 10:41
@EkoJr I assume you'd need <5.4 to reproduce, such as 5.2.4/5.3

**Comment by arnaudbroes** [comment] 2018-03-20 12:59
Perhaps related: https://wordpress.org/support/topic/php-notice-trying-to-get-property-of-non-object-13/

**Comment by michaeltorbert** [comment] 2018-03-20 14:56
@arnaudbroes Nope.

**Comment by wpsmort** [comment] 2018-08-29 19:14
@contactashish13 Can you take a look at this and see if you can figure out how to reproduce the PHP Notices reported here as neither @EkoJR or I can reproduce them.

**Comment by contactashish13** [comment] 2018-08-31 07:35
@wpsmort I'm unable to reproduce these notices as well.

**Comment by michaeltorbert** [comment] 2018-10-09 02:40
@contactashish13 @EkoJR @wpsmort 

What do we think, do we want to just close it (until we gain access to a user's site) since nobody can reproduce it, or do we like the code and figure it probably fixes it?
Personally, I don't like shipping code that we don't know if it actually accomplishes anything.

**Comment by contactashish13** [comment] 2018-10-09 07:11
@michaeltorbert Unless we can test, I feel it's dangerous as it could cause some other unforeseen bug. Might be best to shelve it for the time being.

**Comment by michaeltorbert** [comment] 2018-10-09 14:56
Ok so we're all in agreement to close both issues and their corresponding PRs?

**Closed by michaeltorbert** 2018-10-09 14:56 UTC
Labels: Needs reproducing
