### ISSUE TITLE
Error message: Notice: Undefined variable: post_type in /home/zoes0702/public_html/zoelarkin.com/wp-content/plugins/all-in-one-seo-pack/aioseop_class.php on line 4235

### ISSUE THREAD

**Issue by zoelarkin** [semperfiwebdesign/all-in-one-seo-pack#2116] opened 2018-12-17 18:15 UTC
I know that and have seen the previous thread on this, but it didn't seem to work adding the code that was suggested. 

Pages that it happens are category pages of my blog, showing each category that I have set up on my blog section of my website. 

https://zoelarkin.com/category/engagement-proposal/
https://zoelarkin.com/category/intimate-wedding/ 
https://zoelarkin.com/category/album-print/

like this: http://prntscr.com/lw5w9a 

 - [ ] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [ ] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**
What happened?
What did you expect to happen?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:

**Additional context**

**Comment by michaeltorbert** [comment] 2018-12-17 19:18
So that we don't have to hunt around, please link to things you're referencing, like "the previous thread on this" and "the code that was suggested".

**Comment by michaeltorbert** [comment] 2018-12-17 19:19
@zoelarkin So that we don't have to hunt around, please link to things you're referencing, like "the previous thread on this" and "the code that was suggested".

**Comment by zoelarkin** [comment] 2018-12-17 19:39
Thank you @michaeltorbert ! https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1491 and the code is below. Apologies in advance I'm not a 'github' person and don't know anything about coding. I'm just a photographer. But I'll definitely provide all the info I can!! 

Method 1
Uses the same concept as before, but checks the value.

$haspost = false;
if ( ! empty( $query->posts ) ) {
	$haspost = count( $query->posts ) > 0;
}
Method 2
Uses the built-in function, and would be cleaner.

// OR should it be using a WP function; have_posts()?
$hasposts = have_posts();

**Comment by EkoJR** [comment] 2018-12-17 19:57
Looks like this was introduced in commit ebf2c686fa106e9d0aa908ec68d12ef297780b17

For this, I see a better solution by moving `$post_type = get_post_type();` to the line above the If check.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L4241 to https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/aioseop_class.php#L4223

**Comment by zoelarkin** [comment] 2018-12-19 02:51
@michaeltorbert ooops, so sorry. I'll stay off the thread from now on and let you get on with it

**Comment by wpsmort** [comment] 2018-12-20 19:56
This appears to be a duplicate of #1798 and the proposed change in PR #2117 appears to be the same change that's in PR #1825.  @EkoJR Please confirm this.

I tested PR #2117 but it results in the same problem as I reported here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-412670589 where the nofollow tag is changed.

**Comment by EkoJR** [comment] 2018-12-21 17:41
Looks like it is a duplicate.

Although, it looks like code was duplicated to satisfy the end result. So, I'll need take another look at the function's concept itself, and see if I can refactor it back into 1 code. https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1798#issuecomment-427028209

**Comment by arnaudbroes** [comment] 2018-12-26 09:43
I believe this might be a duplicate of #1985 also.

**Comment by wpsmort** [comment] 2018-12-27 18:13
@EkoJR Feel free to take a look but make sure to discuss with @contactashish13 as he's looked at this code and determined that in order to solve this PHP notice, the code will probably need a complete rewrite.  I'm closing this issue in favor of #1798

**Closed by wpsmort** 2018-12-27 18:13 UTC
Labels: Bug

**Comment by EkoJR** [comment] 2018-12-28 00:05
@wpsmort That does seem to be the case, and I'll probably take a look.
