### ISSUE TITLE
Undefined index: aiosp_opengraph_options in aioseop_opengraph.php on line 1302

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2239] opened 2019-03-02 10:49 UTC
As seen on Olivier S.'s website who reported this on 03-02-2019 in the Premium Forums.

> Notice: Undefined index: aiosp_opengraph_options in .../wp-content/plugins/all-in-one-seo-pack-pro/modules/aioseop_opengraph.php on line 1302

https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/php-error-message/

**Comment by wpsmort** [comment] 2019-03-07 00:53
I believe this is a dupe of #2158 which was fixed in PR #2158

**Comment by arnaudbroes** [comment] 2019-03-13 17:32
I asked Olivier in the Premium Forums which version he is using.

**Comment by michaeltorbert** [comment] 2019-03-13 17:38
He says in there it's Pro 2.13.

**Comment by michaeltorbert** [comment] 2019-05-26 19:10
Can you reproduce this?

**Comment by arnaudbroes** [comment] 2019-05-26 20:42
I can't reproduce it and I don't see any reason why this error would appear since $type doesn't seem to be empty in any scenario.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/3d46a348779d90594ce02f4ed6537b851c07ec2c/modules/aioseop_opengraph.php#L1307-L1321

I'll go ahead and close this issue for now since no one else has reported this.

**Comment by arnaudbroes** [comment] 2019-05-26 20:58
I've asked Olivier in the Premium Forums for access to his website so we can troubleshoot the issue there since we're not able to reproduce it on a test server.

**Comment by michaeltorbert** [comment] 2019-08-15 14:28
Closing as we've not received a response from the one person who reported it.

**Closed by michaeltorbert** 2019-08-15 14:28 UTC
Labels: Bug, Needs Reproducing, User Reported
