### ISSUE TITLE
Bug on Home page since upgrade

### ISSUE THREAD

**Issue by Cranfield-Chronicle** [semperfiwebdesign/all-in-one-seo-pack#3022] opened 2019-11-12 14:16 UTC
Hi,

I'm getting the following message on my homepage since I updated my plug-in today:

Warning: First parameter must either be an object or the name of an existing class in /homepages/34/d681747113/htdocs/app681747174/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 132

Warning: First parameter must either be an object or the name of an existing class in /homepages/34/d681747113/htdocs/app681747174/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 136

Warning: First parameter must either be an object or the name of an existing class in /homepages/34/d681747113/htdocs/app681747174/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 132

Warning: First parameter must either be an object or the name of an existing class in /homepages/34/d681747113/htdocs/app681747174/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 136

All other pages seem to be OK. What do I need to tweak - I'm not a coder, so don;t get too complicated 

My site is using the Divi Extra Theme

**Comment by michaeltorbert** [comment] 2019-11-12 14:24
This is a duplicate of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/3014

**Closed by michaeltorbert** 2019-11-12 14:24 UTC

**Comment by NaszeSzlaki** [comment] 2019-11-12 18:48
> Turn off debug mode on your live site and the message should go away.

Sorry Michael how I can turn off debug mode on my website ? Thx
