### ISSUE TITLE
recent update to all in one seo made CPU usage surge

### ISSUE THREAD

**Issue by gemelli2** [semperfiwebdesign/all-in-one-seo-pack#2652] opened 2019-06-13 15:16 UTC
hi -- i updated to the latest version of the plugin 3.1 and the day after, my hosting company said that the CPU usage was sky high. Apparently (from the siteground tech people) they said that up until i updated the plugin, script executions were taking ~ 0.6 seconds to complete and then after that time, it was taking up to 30 secs.

Also: the most frequently executed scripts seem to be index.php and /wp-admin/admin-ajax.php

Once i reverted the plugin to the older version 3.0.4 from a backup, the CPU usage went down again to normal levels.

**Comment by michaeltorbert** [comment] 2019-06-13 15:28
@gemelli2 

> Once i reverted the plugin to the older version 3.0.4 from a backup, the CPU usage went down again to normal levels.
Thats odd. The only change in 3.1 was to change the naming convention for the XML sitemap files, would wouldn't affect performance. You can submit your login info to our secure form here and we'll take a look: https://semperplugins.com/contact/support-login-information/

> switch to yoast
Obviously we don't recommend that.

**Comment by wpsmort** [comment] 2019-06-13 17:51
@gemelli2 We've tested on your site updating between v2.12.1, v3.0.4 and v3.1 of All in One SEO Pack and are seeing no difference in performance on the site.  We also tested on a clone of your site on our server and there was no difference in performance or CPU utilization.

We did notice three things regarding the configuration of WordPress, they are:

- In the wp-config.php file you have the WP_MEMORY_LIMIT and WP_MAX_MEMORY_LIMIT set to 128M which is very low.  The memory_limit set in the php.ini fie is 758M
- The external object cache is not in use. The Memcached extension for PHP is installed but is not in use by WordPress
- There is no execution time limit. The max_execution_time PHP configuration directive is set to 0

You may want to ask your hosting company if these settings are correct.

**Comment by michaeltorbert** [comment] 2019-06-13 17:55
Can you provide specific instructions on how to see the performance problems on your site?

**Comment by gemelli2** [comment] 2019-06-13 18:04
i saw it in my cpanel.... yesterday the top "last 2 hours" was over the
8000 limit for CPU and and up into the 7k in executions
[image: image.png]


i'm not sure where else you can get that info???


2twinsdesign
website design | graphic design | SEO
Phone & Text: (484) 321-3289
info@2twinsdesign.com | 2twinsdesign.com
[image: cloudHQ]
<https://chrome.google.com/webstore/detail/free-email-tracker/nknojfclnachdkpdkjbbhbkgpnladhnj>
Powered
by
cloudHQ
<https://chrome.google.com/webstore/detail/free-email-tracker/nknojfclnachdkpdkjbbhbkgpnladhnj>

**Comment by michaeltorbert** [comment] 2019-06-13 18:07
Ok offhand I’d say that doesn’t seem to indicate AIOSEOP is involved.

**Comment by gemelli2** [comment] 2019-06-13 18:29
thanks -

i will look into all of these....
i appreciate your input -- not sure why it happened when i updated your
plugin ... weird timing?


2twinsdesign
website design | graphic design | SEO
Phone & Text: (484) 321-3289
info@2twinsdesign.com | 2twinsdesign.com

**Comment by wpsmort** [comment] 2019-06-13 18:41
It could have been any number of things that caused the CPU spike.  I'll close this issue.

**Closed by wpsmort** 2019-06-13 18:41 UTC
Labels: Needs User Input

**Comment by michaeltorbert** [comment] 2019-06-13 21:16
@gemelli2 

Like every software, we've certainly introduced bugs or code that needed some attention, even including some performance issues (though that's rare and generally only for exceptionally large sites). 

Yet, after nearly every release for over a decade, we've received reports that the latest release of x.x caused some sort of performance issue. In reality, what tends to happen is that problems are only noticed after an update, even if the update is unrelated to the problem. For a plugin used on millions of websites, this is bound to happen in nearly every release. Hosts tend to want to pass the buck, and since AIOSEOP is installed on A LOT of websites, it's often the recipient of the blame. Every major plugin, even WordPress itself, has the same experience.
While we diligently investigate all reports of post-update performance problems, in 99% of them it conclusively turns out to be unrelated to AIOSEOP.
In this case, it could be that, or it could be bad timing. Who knows. We've seen it all over the years. Unless we can objectively point to a specific problem that is reproducibly related to AIOSEOP, I'd say it's a coincidence.  

Version 3.1 literally has one change, which is the name of your sitemap file. There is no conceivable way that could have any affect on server resource usage, good or bad.

Having said all that, if you can conclusively identify a problem with AIOSEOP, please let us know and we'll be happy to take a look. :)
