### ISSUE TITLE
Sitemap not being read for several months, Submitted new, still not read

### ISSUE THREAD

**Issue by GaryWicks** [semperfiwebdesign/all-in-one-seo-pack#2184] opened 2019-02-07 15:53 UTC
- [x] I understand that this is a development repository and not a support forum. This is a bug report and is not a support request.
 - [x] I've followed the [troubleshooting steps](https://semperplugins.com/documentation/how-to-troubleshoot-issues-with-all-in-one-seo-pack)  to determine if there's a theme/plugin conflict. 

**Describe the bug**
What happened?
What did you expect to happen?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:

**Additional context**

**Comment by GaryWicks** [comment] 2019-02-07 15:57
latest version of wordpress and all in one plugin all up to date and php 7.2.14
google has not read it since last June

**Comment by michaeltorbert** [comment] 2019-02-07 16:51
There’s not much to go on since you haven’t filled out the form nor provided the URL to your sitemap.

**Comment by GaryWicks** [comment] 2019-02-07 17:26
Sorry, first time here and unaware of requirements and how this site works. How do I supply urls in private view only to semperfi all in one?

**Comment by wpsmort** [comment] 2019-02-07 17:27
@GaryWicks You can use the contact form here - https://semperplugins.com/contact/

**Comment by GaryWicks** [comment] 2019-02-07 17:38
Thank-you.

**Comment by wpsmort** [comment] 2019-02-07 17:46
Your problem is caused by Cloudflare.  If I browse to your as Googlebot I get an Error 523 Origin is unreachable from Cloudflare.  You should exclude your sitemap from Cloudflare and any other caching, minification, etc.   This is not a problem caused by our plugin so I'm closing this issue.

**Closed by wpsmort** 2019-02-07 17:46 UTC

**Comment by GaryWicks** [comment] 2019-02-08 04:09
What is the IP address used by Semper to crawl the site?, So I can whitelist it from all security checks in Cloudfare Where do I find this?

**Comment by arnaudbroes** [comment] 2019-02-08 11:08
We don't crawl websites.
