### ISSUE TITLE
Enfold page builder layout broken

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#2120] opened 2018-12-21 22:27 UTC
Reported by Iskan Ibragimov by email on 12/18.

When the Social Meta module is active, the frontend page layout of a page built using the Enfold theme Avia page builder is broken.

**Comment by wpsmort** [comment] 2018-12-29 19:42
This is quite difficult to reproduce, here are the steps:

Environment: WordPress v5.0.2, AIOSEOP v2.10.2, Enfold v4.5.2

1. Create a page using the Enfold page builder
2. Add a Color Section from the Layout Elements
3. Edit the Color Section and add a Custom Background Image on the Section Background tab
4. Add a Text Block inside the Color Section 
5. Add a Text Block below the Color Section
6. The result should be that when you view the page you see the text block with the image as a background and then below this you should see your other text block.  See screenshot below:

<img width="1361" alt="screen shot 2018-12-29 at 2 35 29 pm" src="https://user-images.githubusercontent.com/17548525/50541592-02f2ef80-0b77-11e9-89bb-111820d80c4f.png">

7. Now activate the Social Meta module in AIOSEOP and enable the Run Shortcodes In Description under Advanced Settings
8. View your page again and you'll see that the background image now runs behind both text blocks. See screenshot below:

<img width="1362" alt="screen shot 2018-12-29 at 2 38 20 pm" src="https://user-images.githubusercontent.com/17548525/50541607-6f6dee80-0b77-11e9-9919-f182fa49e18d.png">

Looking at the HTML in the source code and comparing the page before and after enabling the Run Shortcodes In Description option, I can see that after enabling this option a bunch of </div> are added after the main-title container.  This has the effect of incorrectly closing a bunch of divs.  I cannot figure out why the Run Shortcodes In Description would cause this behavior.

I'm reporting this to the developers of the Enfold theme so they can check this out.

**Comment by InoPlugs** [comment] 2019-02-22 16:18
Hi,

Sorry it took a bit longer but I think I could fix the problem.

I added it to our dev repo for the next release.

I'm not sure why exactly in the example and setting above the shortcodes are called during processing the header. If I load the main page of Enfold 2017 demo which is more complex the header is executed and then the shortcodes are started - sounds strange.

Set a breakpoint in enfold\config-templatebuilder\avia-template-builder\php\shortcode-template.class.php  function shortcode_handler_prepare and you see it.

If you want a copy of this version to test give me your E-Mail and I can send you a copy.

**Comment by michaeltorbert** [comment] 2019-03-13 17:47
@InoPlugs You can send it to support at our domain which is semperplugins dot com. Address it to @arnaudbroes .

**Comment by InoPlugs** [comment] 2019-03-18 13:27
@michaeltorbert 
@arnaudbroes 

Hi, sorry for the late reply. I sent you the latest version (4.5.5 - a beta version shortly to be released).

Let us know if everything is fixed with this version. See also https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2120#issuecomment-466453764

**Comment by arnaudbroes** [comment] 2019-03-18 15:00
@InoPlugs thank you for getting back to us. The issue is fixed in the latest version of the Enfold theme, so I'll go ahead and close this.

**Closed by arnaudbroes** 2019-03-18 15:00 UTC
Labels: Conflict, Has been reproduced, User Reported

**Comment by arnaudbroes** [comment] 2019-03-20 17:44
@InoPlugs your fix seems to have caused #2307. Would you mind having a look at that?
