### ISSUE TITLE
Bug with plug-in All in One Seo Pack e Jannah Theme

### ISSUE THREAD

**Issue by MarioJHJ** [semperfiwebdesign/all-in-one-seo-pack#1930] opened 2018-09-19 14:46 UTC
Hi, is months that I can not update the plug-in “All in One SEO Pack” with Jannah Theme, because in the post/article I do not see more the module of plug-in for data entry, my latest version 2.4.5.1 of the plug-in is working with Jannah theme, from the versions next this module disappear in article. As I do, I can no longer update the plug-in. Please Help me

Theme is: https://themeforest.net/item/jannah-wordpress-news-magazine-theme/19659555

**Comment by michaeltorbert** [comment] 2018-09-19 15:28
I'm not clear on what problem you're reporting exactly. Please follow this template so we can help you: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new?template=bug_report.md

Also, we'll need a copy of the Jannah Theme.

**Comment by MarioJHJ** [comment] 2018-09-20 12:27
Hi,

this module of "All In One SEO Pack" https://imgur.com/a/A8uCXWX 
not see more in Article/Post of Wordpress, this happens from version next 2.4.5.1, so I can no longer update the plug-in.

**Comment by MarioJHJ** [comment] 2018-09-20 12:34
This Theme http://www.filedropper.com/theme_3

**Comment by arnaudbroes** [comment] 2018-10-08 23:09
Duplicate of #1932.

**Closed by arnaudbroes** 2018-10-08 23:09 UTC
Labels: Duplicate
