### ISSUE TITLE
Improve behavior of homepage settings

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1478] opened 2018-01-14 17:20 UTC
Perhaps if a static page is set as the homepage, we should automatically enable the "use static front page instead"?
The only thing wrong with that is if they're still wanting to use the one in general settings.

**Comment by EkoJr** [comment] 2018-01-14 22:21
I was thinking a notification might help to ask the user if they would like to automatically apply the same changes.

**Comment by michaeltorbert** [comment] 2018-08-22 14:31
Suggestion to gray out/disable whichever portion isn't in use https://wordpress.org/support/topic/social-image-settings/#post-10613006

**Comment by wpsmort** [comment] 2019-03-07 22:17
This is a dupe of #495.  I'm moving that issue up to the v3.0 milestone.

**Closed by wpsmort** 2019-03-07 22:17 UTC
Labels: Initial Review, UX
