### ISSUE TITLE
Compatibility issue with WooCommerce & Fusion Builder plugin

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1682] opened 2018-05-08 15:23 UTC
When WooCommerce is installed together with the Fusion theme (and the plugins that come with it), then you're no longer able to select a value in the Product Type dropdown because the window automatically jumps up back to our meta box. 

I already traced this back to 2.2 of the free version.

**Comment by wpsmort** [comment] 2018-05-25 21:58
I tested with the current versions of free (v2.5) and Pro (v2.6) with the default Twenty Seventeen theme and only the Fusion Builder and WooCommerce plugins active and can reproduce the problem.

**Comment by arnaudbroes** [comment] 2018-06-07 18:12
I've e-mailed Theme Fusion to request the latest build of their Fusion Builder plugin since we no longer have access to the client's website.

**Comment by arnaudbroes** [comment] 2018-07-31 21:57
I have access to the repositories of Theme Fusion's plugins and their Avada theme. Contact me in case you need them.

**Comment by michaeltorbert** [comment] 2018-09-09 01:06
@arnaudbroes Are you able to narrow down to a specific commit in 2.2?

**Comment by EkoJR** [comment] 2018-09-23 07:08
The problem occurs because of a patch/workaround, and it appears to be fixed within WP; removing the code resolves the problem, and no issues occur (to my knowledge). 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/js/modules/aioseop_module.js#L294

**Closed** 2018-10-18 20:03 UTC
Labels: Bug, Compatibility, Has been reproduced
