### ISSUE TITLE
Bug - OG:description still output when autogenerate descriptions is disabled

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2998] opened 2019-10-30 21:55 UTC
We fixed this for the regular description in https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2947 but not for the OG:description.

**Comment by wpsmort** [comment] 2020-02-03 18:18
Dupe of #1656

**Closed by wpsmort** 2020-02-03 18:18 UTC
Labels: Bug, Has been reproduced
