### ISSUE TITLE
XML Sitemap Memory

### ISSUE THREAD

**Issue by FilmCutting** [semperfiwebdesign/all-in-one-seo-pack#1200] opened 2017-09-28 22:21 UTC
Hello,

I also installed today’s 2.4 update, and upon doing so my sitemap no longer loads. When I click to view my sitemap, it says:
"XML Parsing Error: no root element found
Location: http://filmcutting.com/sitemap.xml
Line Number 1, Column 1:"

I've deleted cache and also tried resetting my sitemap's settings to the defaults without any results. When I tried to check my sitemap via Google Search Console I also recieved an error. It says:
"We encountered an error while trying to access your Sitemap. Please ensure your Sitemap follows our guidelines and can be accessed at the location you provided and then resubmit... Network unreachable: HTTP Error: 500"

Thank you,
Nick

**Comment by michaeltorbert** [comment] 2017-09-29 01:45
Hi @FilmCutting, unfortunately we've not been able to reproduce this issue. You can submit your login info to our secure form here and we'll be happy to take a look: https://semperplugins.com/contact/submit-login-information/

**Comment by FilmCutting** [comment] 2017-09-29 06:36
Hi michaeltorbert, thank you for your prompt reply. I have submitted my login info to your secure form. Kind regards.

**Comment by michaeltorbert** [comment] 2017-09-29 09:47
@FilmCutting Can you check your apache logs for any errors?

**Comment by FilmCutting** [comment] 2017-09-29 09:59
Sorry, but I don't know how to check my apache logs. I have logged in now to my admin successfully. Do you have problem to log in? I have Login LockDown plugin installed (Adds some extra security to WordPress by restricting the rate at which failed logins can be re-attempted from a given IP range).

**Comment by michaeltorbert** [comment] 2017-09-29 10:01
@FilmCutting There's no problem logging in. We just want to check the apache logs for any clues as to the problem with the sitemap. If you submit the form again with your FTP login information I'll see if I can find the logs. https://semperplugins.com/contact/submit-login-information/

Also, who is your hosting company?

**Comment by FilmCutting** [comment] 2017-09-29 10:03
Thank you. I will do it right now. My hosting company is MochaHost.

**Comment by FilmCutting** [comment] 2017-09-29 10:24
Dear Michael, the sitemap in online again! Thank you a ton! Should I keep the default settings (19 sitemaps) or check just for posts and pages?

**Comment by michaeltorbert** [comment] 2017-09-29 10:30
@FilmCutting The problem is almost certainly memory, but we're still making a backup of your site to our private server for testing. 
To fix it for you I just enabled to use sitemap indexes, so each sitemap is smaller and takes up less memory. We'll release an update to resolve this though.

**Comment by FilmCutting** [comment] 2017-09-29 10:41
Ah, so! I'm not a tech person. I will not touch anything and will be waiting for your update. Thanks again for helping me.

**Comment by michaeltorbert** [comment] 2017-09-29 10:45
Ok the backup has completed to our servers. The sitemap works on our servers perfectly. We've confirmed the problem is memory.

We'll have a release soon that optimizes memory usage, but we recommend anyone else reading this to take the following steps in the meantime:

1) In the XML Sitemap module, enable the Sitemap Indexes option, then enable paginate sitemap indexes. In "Maximum Posts Per Sitemap," choose a low enough number that you don't run out of memory and your sitemap works. It may be 1,000 or it may be 10,000.

2) Increase PHP memory to 256 or even 512 https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP

Either of these should fix it.

**Comment by FilmCutting** [comment] 2017-09-29 10:56
I can confirm that the first step is already made - the max. posts per sitemap is set to 1,000. The memory limit is also set to 256 (which is the max. value).

**Comment by michaeltorbert** [comment] 2017-09-29 10:59
Yes, I did that for you. Those instructions were for anyone else reading.

**Comment by FilmCutting** [comment] 2017-09-29 11:11
Note: I've just checked my Google search console. It says: https://screenshots.firefox.com/8tvW2NA5NEYD65Ft/www.google.com
I don't know if that report is accurate or not as I am able to reach the sitemap_post_3 link?!

**Comment by FilmCutting** [comment] 2017-09-29 11:15
I've just tested sitemap. Everything seems alright now: https://screenshots.firefox.com/k6qOg5skQjYkp4uS/www.google.com

**Comment by FilmCutting** [comment] 2017-09-29 12:21
Sadly, Google search console still not validate the above sitemap: https://screenshots.firefox.com/LUg8D0O4e6jOzjZr/www.google.com

**Comment by wpsmort** [comment] 2017-09-29 22:03
@FilmCutting I've opened a separate issue for the validation error here - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1212

**Comment by FilmCutting** [comment] 2017-09-29 22:12
Thank you. Earlier today some of your colleagues installed Cloudways Migrate plugin on my site in order to backup it. Do you still need the plugin for testing?

**Comment by wpsmort** [comment] 2017-09-29 22:18
@FilmCutting I have deleted that plugin from your site.

**Comment by FilmCutting** [comment] 2017-09-29 22:42
Thank you. Do you recommend all post types and taxonomies to leave checked?

**Comment by wpsmort** [comment] 2017-09-29 22:44
@FilmCutting You can uncheck Media / Attachments and Format.

**Comment by FilmCutting** [comment] 2017-09-29 22:48
Thanks for sharing your knowledge!

**Comment by contactashish13** [comment] 2017-10-02 13:24
@michaeltorbert PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1223

The two improvements in this are:

1) For featured image
a) check whether the post type supports thumbnails
b) check if the attachment in the featured image is an image

2) For post type 'attachments'
a) check if the attachment in the featured image is an image

**Comment by wpsmort** [comment] 2017-10-02 18:54
@contactashish13 I tested PR #1223 and this no longer gets featured images when they are set in a post and displayed on the front end of the post.  To replicate this, follow these steps:

1. Create a new post and set a featured image and add an image into the content
2. With v2.4, check the sitemap and you should see two images listed for your new post, the featured image and the image in the content
3. Now test with your PR and you'll see only one image listed, the image in the content

**Comment by michaeltorbert** [comment] 2017-10-02 19:17
I'm moving this away from 2.4.1, as it doesn't appear we can make major memory improvements to the current code. Indexes are the future. :)

**Comment by contactashish13** [comment] 2017-10-03 08:06
@wpsmort I've removed the check mentioned in 1b. Now only 1a and 2a are valid checks. I've tested with multiple cases and this is now working fine.

I've also synced this PR with the upstream dev

**Comment by contactashish13** [comment] 2018-02-06 06:26
@wpsmort You've assigned this to me but I don't see any comments so I'm not sure what needs to be done here.

**Comment by wpsmort** [comment] 2018-02-06 17:43
@contactashish13 Please update PR #1223 to sync with the current version of master and resolve the conflicts.

**Comment by contactashish13** [comment] 2018-02-07 07:00
@wpsmort have synced with master and also added test cases for testing image count.

**Comment by contactashish13** [comment] 2018-09-28 06:05
While redoing the PR I realized that this issue might no longer be relevant as https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1828 handles memory issues. @wpsmort please confirm.

**Comment by wpsmort** [comment] 2019-01-29 21:39
PR #1828 resolved the memory issues and this has also been superseded by the recent sitemap optimizations in PR #2136

**Closed by wpsmort** 2019-01-29 21:39 UTC
Labels: Bug, Needs Testing, Priority | High
