### ISSUE TITLE
Conflict with EWWW.io plugin

### ISSUE THREAD

**Issue by sporkman** [semperfiwebdesign/all-in-one-seo-pack#2268] opened 2019-03-08 21:51 UTC
When installing the latest EWWW.io cloud version (https://wordpress.org/plugins/ewww-image-optimizer-cloud/), some type of JS issue is introduced in AIOSEO's admin-side javascript:
![screenshot-dt 2019-03-08 at 4 33 17 PM](https://user-images.githubusercontent.com/510750/54057980-79891a80-41c2-11e9-8b79-99c95b3336ce.png)

**Comment by arnaudbroes** [comment] 2019-03-11 18:50
@sporkman I'm not able to reproduce this with the latest version of EWWW Image Optimizer Cloud and All in One SEO Pack. I went through all menus of both EWWW.io Cloud and AIOSEOP with the dev console and I didn't see any errors. 

Please provide us with a list of any other plugins you're using, your theme, tell us where this is happening and if possible how we can reproduce the issue.

**Comment by arnaudbroes** [comment] 2019-03-13 16:41
@sporkman just a reminder that we need your input here, otherwise we'll have to close this issue as we're not able to reproduce this.

**Comment by sporkman** [comment] 2019-03-13 17:34
Hi - I'm not seeing this in the settings for either, it's coming up when editing some custom post types. Without the dev console open, it presents as the page being unresponsive, but that's just the result of most of the javascript not firing. If I had to guess, the issue is somewhere in the AIOSEOP editor snippet where one is able to add featured images for social networking.

Lots of plugins - if you can leave this open for a few more days, I can strip this all the way down to just Ewww and AIOSEOP and tell you if it still happens.  But the list, for the record, is:

ACF
ACF Component Field
ACF Contact Form 7
Classic Editor
Contact Form 7
Contact Form 7 - recaptcha v2
Contact Form 7 - Drag and Drop Files Upload - Multiple Files Upload
Duplicate Post
Dynamic Select for CF7
Enhanced Media Library
Query Monitor
Redirection
Relevanssi Premium
Reorder by Term
Reorder Posts
Search Regex
User Registration
WP Disable

**Comment by arnaudbroes** [comment] 2019-03-18 19:44
@sporkman I'm not able to reproduce this with those plugins either so I'll go ahead and close this for now, but please feel free to reopen this if you have any new leads. 

I'd recommend you to disable all your plugins besides AIOSEOP, switch to the default Twenty Seventeen theme and then start by reactivating them one by one to narrow it down.

**Closed by arnaudbroes** 2019-03-18 19:44 UTC
Labels: Awaiting User Input, Needs Reproducing, User Reported
