### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by PhearomVon** [semperfiwebdesign/all-in-one-seo-pack#2685] opened 2019-06-25 09:37 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by arnaudbroes** [comment] 2019-06-25 10:26
@PhearomVon You didn't fill in the issue template or tell us what the problem is, so I'm going to close this issue. Feel free to reopen the issue if you can provide us with information about the problem that you are experiencing.

**Closed by arnaudbroes** 2019-06-25 10:26 UTC
