### ISSUE TITLE
Bug - Robots meta tag doesn't have correct closing tag

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2866] opened 2019-09-05 10:48 UTC
https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/851e11af3cf4832253ea036348ae46f164c5d235/aioseop_class.php#L4243-L4245

This should be a correct self-closing tag (`< />` instead of `<>`).

**Comment by michaeltorbert** [comment] 2019-09-06 19:01
Duplicate of #2876
Closing this in favor of that one since it has more info.

**Closed by michaeltorbert** 2019-09-06 19:01 UTC
Labels: Bug
