### ISSUE TITLE
Escaping the quotes

### ISSUE THREAD

**Issue by martinytodorov** [semperfiwebdesign/all-in-one-seo-pack#593] opened 2016-10-13 00:30 UTC
Hi there, thanks for the great plugin.

An editor in my website somehow input a quote (") and this messed up the twitter card.
Now I have to change it in the database, cause the description box is disabled.
Can you see if these special chars are all escaped for the next version.

Cheers,
Martin

**Comment by michaeltorbert** [comment] 2016-10-13 00:44
Hi Martin,

Quote should be escaped in meta descriptions for posts. 
Where are you seeing this?

**Comment by martinytodorov** [comment] 2016-11-10 00:18
Hey Michael, I though the problem might be in our editorial, but it happened again. It only happens to articles that have quotes into the beginning of the body. See this:
http://dailynexus.com/2016-11-08/fuck/

**Comment by arnaudbroes** [comment] 2017-05-06 22:34
Tested and confirmed.

**Comment by wpsmort** [comment] 2017-06-06 16:21
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/meta-descriptions-double-quotes-not-escape/#p6650

**Comment by amostajo** [comment] 2017-06-07 00:27
@wpsmort I am not being able to reproduce the error. Not sure if PR #901 solved it, cus it decodes html entities.
I tried this with multiple scenarios, double quotes in excerpt, content, as html entity... and aioseop supports them pretty well.

**Comment by arnaudbroes** [comment] 2017-06-07 08:06
I'll check this.

**Comment by arnaudbroes** [comment] 2017-06-07 08:27
I'm still getting this with the latest version of Free and Pro. 
Tested with one post with a manually added description and one post with a auto-generated description.
view-source:http://wordpress-72523-276765.cloudwaysapps.com/
PM me on Slack @amostajo if you want credentials to the test site. :-)

**Comment by michaeltorbert** [comment] 2017-06-07 10:53
Reported again here:

https://wordpress.org/support/topic/ogp-tags-in-2-3-13-2-is-unescaped/

**Comment by wpsmort** [comment] 2017-06-07 14:23
@amostajo There are two problems here:  

The first only affects the og:description and twitter:description.  In the screenshot provided by @arnaudbroes above, you can see that we output " in the meta tag which breaks the HTML because you can't have double quotes inside content="".  This is reflected by the color of the text where the HTML tag has been closed by the ".

The second problem is that we're not standardized on our use of character codes.  In the title tag, og:title and twitter:title we're using &#8220; and &#8221; but in the meta description we're using &quot;.  I think we need to standardize on &quot;.

**Comment by michaeltorbert** [comment] 2017-06-08 14:26
Reported again here: https://wordpress.org/support/topic/glitch-in-social-media-settings-snippet

**Comment by wpsmort** [comment] 2017-06-08 15:13
I tested PR #930 and found two bugs.  I updated the PR with the details.

**Comment by wpsmort** [comment] 2017-06-08 18:18
@amostajo I tested PR #930 and found one issue I updated the PR with the details.

**Comment by wpsmort** [comment] 2017-06-09 16:55
This is tested and now works fine.  I've tested with PHP versions from 5.2 to 7.1 and all work.  

PR #930 is now ready for code review.

**Closed** 2017-06-29 19:15 UTC
Labels: Enhancement
