### ISSUE TITLE
% in title breaks title format macros

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#2111] opened 2018-12-15 15:16 UTC
Placing an % in the title seems to break all macros (e.g. %post_title%) that follow after it.

In order to reproduce this issue, follow these steps:

1. Install All in One SEO Pack on a new test site
2. Go to the General Settings and set the title format of Posts (example) to %post_title% | %post_title%
3. Create a new Post and add a random title without a %. You'll see that the title is just fine.
4. Add a % to the title. You'll see that the second macro breaks.

**Comment by michaeltorbert** [comment] 2019-05-28 23:17
Offhand the only things I can think of to resolve this are either

1) Change all % to %%. In addition to the possible problems coming from doing a db change that massive, we couldn't know when it's intentional.
2) Some method of escaping what's added explicitly to the title on per post basis.

**Comment by arnaudbroes** [comment] 2019-05-29 13:32
@michaeltorbert I think I've inadvertently already fixed this with https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2360 by specifying the offset. I just had a look at it and it seems fixed.

@wpsmort can you confirm this with the 3.0 branch and close the issue if I'm correct?

**Comment by michaeltorbert** [comment] 2019-05-29 13:43
@wpsmort 
If this has been fixed, we'll include the issue in 3.0 and close it.
If not, send it Back to the Future.

**Comment by wpsmort** [comment] 2019-05-29 16:32
I was unable to reproduce this and after speaking with Arnaud we found it was an error in his testing procedure (he'd left a % off the end of the %post_title% macro).

However, we did confirm there is a bug with percent signs in the preview snippet.  See #2526

**Closed by wpsmort** 2019-05-29 16:32 UTC
Labels: Invalid
