### ISSUE TITLE
Additional Character Stops Facebook Excerpt

### ISSUE THREAD

**Issue by H-K-P** [semperfiwebdesign/all-in-one-seo-pack#943] opened 2017-07-01 15:48 UTC
@hallsofmontezuma

Thanks for your reply on WP.org

The known quote issue also extends to an open square bracket "**[**" 
An open square bracket ends a Facebook excerpt as does an **"** 
I have not tested other characters.

Regards, Angus

**Comment by michaeltorbert** [comment] 2017-07-01 16:02
@H-K-P To what issue are you referring?

**Comment by H-K-P** [comment] 2017-07-01 16:21
Hi Michael,
About 3 weeks ago you wrote on your plugin Wordpress.org forum:
_"As for the quote issue, thank you for reporting it. We’re aware of the problem and are currently working on a fix. The best way to report a bug is to open a Github issue https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/new"_
Sorry for the confusion - i was just adding that I found that both " and [  will terminate a Facebook except.

Regards, Angus

**Comment by michaeltorbert** [comment] 2017-07-01 21:32
I have no idea what you're talking about as we have hundreds of open issues. Do you have a link to the issue or the wp.org thread?

**Comment by H-K-P** [comment] 2017-07-01 23:26
Thank you kind sir.  Sorry for the trouble.
https://wordpress.org/support/topic/glitch-in-social-media-settings-snippet/  refers.

**Comment by michaeltorbert** [comment] 2017-07-03 16:52
This may be related to #593 
@wpsmort Can you verify this issue in 2.3.13 and see if https://github.com/semperfiwebdesign/all-in-one-seo-pack/commit/3f579ce3cb1f456d8d0d93ccefccb678751906f1 fixed it?

**Comment by wpsmort** [comment] 2017-07-06 21:35
@michaeltorbert I have confirmed that this is an issue.  It does not get fixed by 3f579ce. Here is the output meta when brackets are included in the title and description:

```
<title>OG Title with [square brackets] in it | Steve Mortiboy</title>
<meta name="description"  content="OG Description with in it - July 6, 2017" />

<meta property="og:title" content="OG Title with [square brackets] in it" />
<meta property="og:description" content="OG Description with in it" />

<meta name="twitter:title" content="OG Title with [square brackets] in it" />
<meta name="twitter:description" content="OG Description with in it" />
```

You'll notice from the above that the titles are all fine but that the descriptions are missing any text that is wrapped in brackets.

**Comment by wpsmort** [comment] 2017-07-06 22:58
I have tested with other special characters and found the exact same issue with < > characters:

```
<title>OG Title with  in it | Steve Mortiboy</title>
<meta name="description"  content="OG Description with in it - July 6, 2017" />

<meta property="og:title" content="OG Title with &lt;greater and less than&gt; in it" />
<meta property="og:description" content="OG Description with in it" />

<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="OG Title with &lt;greater and less than&gt; in it" /
```

**Comment by wpsmort** [comment] 2017-07-19 16:26
I have tested with other special characters and found a similar issue with < > characters:

When text is wrapped in < > characters the text is not output in the doc title, meta description, OG and Twitter descriptions (OG and Twitter titles are fine).  For example: `<greater and less than>` is missing in the source code below:
```
<title>OG Title with  in it | Steve Mortiboy</title>
<meta name="description"  content="OG Description with in it - July 6, 2017" />
<meta property="og:description" content="OG Description with in it" />
<meta name="twitter:description" content="OG Description with in it" />
```

This is not an issue if the < > signs are separated by spaces from the text, i.e This is < or > ten.

@michaeltorbert Two questions here:  
1). In WordPress, text wrapped in [ ] is a shortcode and we try to run the shortcode  This was because some theme visual builders wrap text in shortcodes and we had to run the shortcode to get the text.   
2). Do we want to support text wrapped in < > symbols?  I noticed from typing this comment that Github doesn't display text wrapped in < > unless you format it as code.

**Comment by michaeltorbert** [comment] 2017-08-02 22:34
Strangely it doesn't strip it out in the meta description for me

<img width="611" alt="screen shot 2017-08-02 at 6 33 29 pm" src="https://user-images.githubusercontent.com/17364998/28897927-1fd32f08-77b1-11e7-9733-689114975b3e.png">
<img width="580" alt="screen shot 2017-08-02 at 6 33 19 pm" src="https://user-images.githubusercontent.com/17364998/28897926-1fd30e42-77b1-11e7-9a7d-c8613aa2754a.png">
<img width="523" alt="screen shot 2017-08-02 at 6 33 03 pm" src="https://user-images.githubusercontent.com/17364998/28897928-1ffe59da-77b1-11e7-95b3-1f918e5e8a3c.png">

**Comment by amostajo** [comment] 2017-08-02 22:53
It does for me

**Comment by wpsmort** [comment] 2017-08-03 18:28
PR #1020 fixes the issue with text wrapped in brackets.  It does not fix the issue with text wrapped in greater than and less than symbols which we agreed we would leave for now.

I did find one small odd little bug when testing with greater than and less than symbols.  If the last character in your post title is a less than symbol then we don't output it.  I've opened a new issue #1021 for this.

**Closed** 2017-08-03 18:30 UTC
Labels: Bug
