### ISSUE TITLE
Undefined variable: post_type in aioseop_class.php on line 4251

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1985] opened 2018-10-19 03:02 UTC
Reported here: https://wordpress.org/support/topic/updated-to-2-8-still-see-undefined-variable-error-line-4181/#post-10794921

Looks like $post_type didn't get a value yet. Looking at the code, $post_type = get_post_type() comes later in an elseif

**Comment by wpsmort** [comment] 2018-10-19 14:08
Possibly a duplicate of #1798

**Closed** 2019-03-07 00:29 UTC
Labels: Bug
