### ISSUE TITLE
Summary large image the default for twitter is not working from a few days ago.

### ISSUE THREAD

**Issue by mycreatesite** [semperfiwebdesign/all-in-one-seo-pack#1695] opened 2018-05-20 13:37 UTC
Setting default twitter card as "Summary large image" has not been  working  for a few days ago.
I think it has happened from updating wordpress.

**Comment by Tydbyte** [comment] 2018-07-11 21:05
I am having the same problem.
Any word on if this can be fixed?
Thanks.

**Comment by arnaudbroes** [comment] 2018-09-08 20:01
@michaeltorbert I checked this on a new test site and this still works as it should. New posts/pages inherit the default setting for the Twitter card. I'll close this for now.

@mycreatesite @Tydbyte since we're not able to reproduce this issue, we're closing it for now. Feel free to reopen it in case you're able to tell us the exact steps to reproduce this issue.

**Closed by arnaudbroes** 2018-09-08 20:01 UTC
Labels: Couldn't reproduce
