### ISSUE TITLE
Setting 'Media' to 'Noindex' Does Not Set Noindex On Media Attachment Pages

### ISSUE THREAD

**Issue by jwbats** [semperfiwebdesign/all-in-one-seo-pack#1937] opened 2018-09-23 15:28 UTC
How to reproduce:

1. Go to settings for all in one seo pack.
2. In the noindex settings, check 'media' for 'default to noindex'.
3. Check out an existing media attachment page's source to search for the noindex attribute.
4. Add new media attachment page by uploading an image.
5. Check out the new media attachment page's source to search for the noindex attribute.
6. Observe that there is no noindex attribute to be found in the source for media attachment pages.

Expected behavior:

Noindex on existing/new media attachment pages when this setting is checked.

Version Info:

 - WordPress version: 4.9.8
 - All in One SEO Pack version: 2.8
 - PHP version: 7.2.10

Additional context:

When editing a media attachment page in WP, I don't see any option to manually set it to noindex at all. Also not in the screen options tab. Is it even possible to set media attachments to noindex at all?

If not, then what if Google's crawler accidentally gets wind of your media attachment pages and starts indexing them all? The effect on your rankings could be devastating.

**Comment by michaeltorbert** [comment] 2018-09-23 16:10
Duplicate of #1797

**Closed by michaeltorbert** 2018-09-23 16:10 UTC
