### ISSUE TITLE
Check if image url exists and/or is a string

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1443] opened 2018-01-01 23:09 UTC
Reported here: https://wordpress.org/support/topic/problem-generating-xml-sitemap/

We don't know for certain what the result of wp_parse_url( $image, PHP_URL_PATH ) is for this user, but it's not a string for some reason. We should make sure we're verifying this.

**Comment by contactashish13** [comment] 2018-01-02 05:23
@michaeltorbert This issue appears to be a duplicate of #1355. PR #1356 resolves this.

**Closed** 2019-03-25 21:53 UTC
Labels: Bug, User Reported
