### ISSUE TITLE
Sitemap indexes cannot be viewed when compression is enabled

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/all-in-one-seo-pack#1361] opened 2017-11-13 17:56 UTC
![image](https://user-images.githubusercontent.com/18156697/32740778-4b1aadd2-c8a4-11e7-8e84-e237a58aa285.png)

**Comment by contactashish13** [comment] 2017-11-14 06:59
@arnaudbroes can you please let me know the steps to reproduce this issue? Can I also get access to the cloned site and the SSH instance? If you want, you can make this site available to me through cloudways - will send my email ID on slack.

**Comment by arnaudbroes** [comment] 2017-11-14 23:53
@contactashish13 we don't have a cloned site for this issue. 
Follow these steps to reproduce the issue:

1. Install a fresh, clean test site
2. Install All in One SEO Pack 
3. Create a few dummy posts and pages
4. Activate the XML Sitemap Module in the Feature Manager
5. Check if the 'Create compressed sitemap' setting is enabled
6. Enable the 'Enable sitemap indexes' setting
7. Update and view the sitemap

**Comment by contactashish13** [comment] 2017-11-15 05:04
What should I find in the sitemap and what is the expected behavior?

**Comment by arnaudbroes** [comment] 2017-11-15 05:56
@contactashish13 if you go to /sitemap.xml/, you'll see that the browser displays URLs with the .gz extension, which shouldnt be the case. In addition, when you click on any of the URLs in the sitemap, you won't be able to access them (or depending on the browser it will download the .gz file).

Normal behaviour is that the sitemap does not display the .gz extension and every URL can be opened.

**Comment by contactashish13** [comment] 2017-11-15 11:36
@arnaudbroes I'm not sure I understand the problem. From what I have been reading (e.g. https://www.design19.org/blog/optimize-sitemap-xml-gz-better-seo/) a compressed sitemap is indeed a gzipped file. If thats not the case, then what should compression really do?

**Comment by michaeltorbert** [comment] 2017-11-15 15:09
@contactashish13 The problem is that when sitemap indexes is enabled, the compressed file is a 404.

**Comment by tonyzeoli** [comment] 2017-12-11 21:07
Please note that when I disabled compression on https://janetwhitworth.com, then resubmitted the sitemap to GWT, all 6 errors went away. So it's only the compression that throws the 404 errors in GWT.

**Comment by EkoJr** [comment] 2018-01-03 13:46
This appears to be related to #1428. Which also has a PR.

**Comment by tonyzeoli** [comment] 2018-02-22 16:19
I just got this on a brand new site I'm setting up - 5pointz.com.

1.  Activated XML Sitemaps.
2. Gzip was already enabled, so I didn't touch that.
3. I activated Indexes and set to 1000 per the instructions I got from Steve some time ago when that feature was introduced.
4. Submitted sitemap to Google Search Console
5. Sitemap.xml was accepted, but show:

General HTTP error: 404 not found
Sitemap: 5pointz.com/.xml.gz
HTTP Error: 404

On the compressed sitemap.

6. Turned off compression
7. Resubmit sitemap
8. Waiting for Google update

**Comment by wpsmort** [comment] 2018-04-10 22:08
Reported again here https://semperplugins.com/support/configuring-all-in-one-seo-pack-pro/sitemap-errors-1/

**Comment by michaeltorbert** [comment] 2018-05-03 18:13
Reported again https://wordpress.org/support/topic/sitemap-gz-issue/#post-10244185

**Comment by arnaudbroes** [comment] 2018-06-07 19:21
Reported again here - https://wordpress.org/support/topic/sitemap-not-using-correct-rewrite-rules/

**Comment by arnaudbroes** [comment] 2018-06-09 12:58
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/xml-gz-path-in-sitemap-404-error-search-console/#p7876

**Comment by tonyzeoli** [comment] 2018-10-04 21:49
Do you guys have any information on this.

I have another site, https://pleasantgreenfarms.com, which also recently experienced this issue. In the newly redesigned Google Search Console, the error messages is that the sitemap is not in the proper format. I had to remove compression and resubmit.

**Comment by wpsmort** [comment] 2018-10-04 22:34
@tonyzeoli We do not have any update at this time.  It's assigned to a developer for this next release and marked as high priority.

**Comment by tonyzeoli** [comment] 2018-10-05 00:47
Okay, great. I can confirm tonight that once I disabled compression, I resubmitted the sitemap and it was then accepted. So, the issue still persists for me. Look forward to it.

**Comment by contactashish13** [comment] 2018-10-05 09:55
@wpsmort this is waiting for you or @arnaudbroes's comments: https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1361#issuecomment-344621510

**Comment by arnaudbroes** [comment] 2018-10-05 13:46
@michaeltorbert here are my thoughts:

1. Sitemap compression should NOT be enabled by default as this functionality is only useful for users who have a substantial amount of URLs (at least that's my opinion on it).

2. When sitemap compression is enabled, the XML Sitemap menu shouldn't link to the compressed version since you can't view the contents of the archive in your browser and you will simply download the file instead. Users click the link to check if their sitemap is working, so I would keep this as is. 

However, I would suggest we display some notification at the top of the menu that mentions the link to the compressed version of the sitemap and tells users they should enter that link for their sitemap in Google Search Console, Bing Webmaster Tools, etc. Otherwise I see no point in offering sitemap compression as a feature since most users will simply keep using their uncompressed version.

3. Similar to 2.: if both sitemap indexing and compression are enabled, then users should still get to see the uncompressed versions of their sub sitemaps. Otherwise they're not able to access them and check if everything looks alright. Again, I recommend displaying a notification at the top that mentions which specific URLs they should use to add their sitemap to Google Search Console, Bing Webmaster Tools and the like.

**Comment by michaeltorbert** [comment] 2018-10-05 19:46
Since there's no existing PR, this should not be in 2.9. I've bumped it to 3.0.

@arnaudbroes 

We may want to consider that domain.com/sitemap.xml and domain.com/sitemap.xml.gz both work (I think that may be the case currently) and that just the uncompressed one shows up in the sitemap, then users can use either URL (we need to make it clear in the UI this is the case).
Then we don't even need an option, since both happen anyway.

**Comment by arnaudbroes** [comment] 2018-10-06 18:39
@michaeltorbert even better, let's do that. 

@contactashish13 this is what we want:

1. The "Sitemap Compression" setting is removed, and instead, we generate both an uncompressed version and compressed version of the sitemap(s) by default. 

2. The "view sitemap" link at the top of the menu links to the uncompressed version of the sitemap(s) so that users are able to view and browse through their sitemap(s) to check if everything looks good. 

3. The UI needs to make clear that users can either use the link to the uncompressed version(s) or compressed version(s) when they add their sitemap in Google Search Console, Bing Webmaster Tools, etc.

**Comment by arnaudbroes** [comment] 2018-10-06 18:50
We have #945 open for the 404 error.

**Comment by tonyzeoli** [comment] 2018-10-07 04:07
Hey Arnaud,

I'm not sure, but I thought I'd bring something up. If you use compression,
are you supposed to resubmit your sitemap not as sitemap.xml but
sitemap.xml.gz, because if so, I never knew that and it's not clear to me
if you're supposed to do that. Could that be why Google is throwing an
error, because I am not submitting it as .xml.gz?

If so, then maybe there should be some note near the compression tick box
that says, if you use compressing, then resubmit your sitemap using the
.xml.gz extension.


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
A  310 Roxbury Pl, Arden NC 28704
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  az@digitalstrategyworks.com
<az@digitalstrategyworks.com>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
<https://calendly.com/tonyzeoli> Schedule a 30-minute Meeting
<https://calendly.com/tonyzeoli>
<https://digitalstrategyworks.com/pmpress-5-team-communication/2018/03/22/2333/>
Latest
post: PMPress #5: Team Communication
<https://digitalstrategyworks.com/pmpress-5-team-communication/2018/03/22/2333/>
<https://facebook.com/digitalstrategyworks>   <https://twitter.com/dswks>
<https://linkedin.com/in/+tonyzeoli>
<https://www.youtube.com/+digitalstrategyworks>


<https://gsuite.google.com/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=https://goo.gl/BG4yH8>

**Comment by arnaudbroes** [comment] 2018-10-07 16:08
@tonyzeoli you need to specifically submit it as yourdomainname.com/sitemap.xml.gz, but that's not causing the 404 error since the uncompressed version is still available at yourdomainname.com/sitemap.xml when compression is enabled. We just decided on adding a notification to the UI when sitemap compression is enabled, so that takes care of this.

I believe the 404 error is specific to nginx web servers so we're going to discuss that in #945.

**Comment by contactashish13** [comment] 2018-10-08 10:03
@arnaudbroes I don't think https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1361#issuecomment-427596928 will work because the user now has no way of specifying which sitemap to specify 

1. in robots
2. while pinging google and bing (this is happening without a UI)

I think we should rename the option "Create Compressed Sitemap" to "Link to Compressed Sitemap". If this is checked, then the compressed sitemap will be created and the above 2 destinations will be linked to it. This way the user will always be able to see only the regular sitemap even though the search engines etc. are using the compressed one. Let me know what you think.

**Comment by wpsmort** [comment] 2019-03-07 23:01
@contactashish13 Here's a synopsis of what needs to be done.  This has been discussed thoroughly, we just need a PR.

1. Remove the Create Compressed Sitemap (this is being done under #534)
2. Retain the functionality in the code that creates the compressed sitemap
3. Only display links to the uncompressed sitemaps in the sitemap index
4. Only display the link to the uncompressed sitemap in the robots.txt.  This applies to the robots.txt generated by WordPress and the one generated by AIOSEOP
5. Pings should send the URL for the uncompressed sitemap

Please contact me via Slack if you have any questions.

**Comment by contactashish13** [comment] 2019-03-09 06:19
PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2269

**Comment by michaeltorbert** [comment] 2019-03-09 19:34
> PR #2269
> 
> please note that when indexes are enabled, the GZ file will contain an XML index file and that XML index file will refer to individual XML sitemap files not XML.GZ sitemap files

That's not great behavior. Considering we're planning on moving to index files by default (and maybe even removing the option to not have and index file), I wonder if we should just abandon compression. Thoughts? @wpsmort @contactashish13

**Comment by arnaudbroes** [comment] 2019-03-11 08:43
I would abandon compression in favour sitemap indexes. I don't feel like we still need it at this point and it's causing a boatload of issues.

**Comment by wpsmort** [comment] 2019-03-11 13:49
I am fine with abandoning sitemap compression.  

We'll need to make absolutely sure that all .xml.gz URLs redirect to the uncompressed URL.  This is so that if users have submitted the compressed sitemap URLs to search engines, then search bots will get the uncompressed sitemap when fetching the compressed URL.

**Comment by michaeltorbert** [comment] 2019-03-11 13:51
We'll need to make a point about this in the changelog and release post that we've dropped compression for sitemaps and that they may want to resubmit their sitemaps but that we've redirected them as well.

**Comment by michaeltorbert** [comment] 2019-05-11 14:41
As we're doing away with compression, this can be closed.

**Closed by michaeltorbert** 2019-05-11 14:41 UTC
Labels: Bug, In Development, Priority | Medium
