### ISSUE TITLE
Warning: “continue” targeting switch is equivalent to “break”

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#2129] opened 2019-01-07 14:04 UTC
Reported here: https://wordpress.org/support/topic/warning-continue-targeting-switch-is-equivalent-to-break-3/

> Warning: “continue” targeting switch is equivalent to “break”. Did you mean to use “continue 2”? in /data01/virt71886/domeenid/www.xyz.ee/wp-content/plugins/all-in-one-seo-pack/modules/aioseop_opengraph.php on line 853

**Comment by michaeltorbert** [comment] 2019-01-27 03:16
I'm bumping this to medium priority since a PR has been submitted.
@arnaudbroes Can you try and reproduce this, then assign the PR to a developer for code review?

**Comment by arnaudbroes** [comment] 2019-01-27 14:48
@michaeltorbert I'm not able to reproduce this issue on a test site with WordPress 5.0.3, running on a web server that uses PHP 7.3. 

However, after some research (https://core.trac.wordpress.org/ticket/44543), I was able to reproduce this issue (the notice disappeared after a refresh) on WordPress 4.9.8. It seems this is a WordPress Core bug that was fixed in 5.0. 

I've reached out to those two users in the WordPress.org support thread and asked them to update to a version higher than 4.9.8 to see if that resolves the issue. If it does, then I'll go ahead and close this issue.

**Comment by arnaudbroes** [comment] 2019-01-27 15:05
Nevermind, I was now able to reproduce this - 
![image](https://user-images.githubusercontent.com/18156697/51802763-642ce200-224d-11e9-9bce-ab83dee4ca74.png)

**Comment by gfrino** [comment] 2019-01-29 21:20
have the same problem right after installing it in ticinoweb.net

**Comment by wpsmort** [comment] 2019-02-07 18:06
Reported again here - https://wordpress.org/support/topic/did-you-mean-to-use-continue-2/

**Comment by wpsmort** [comment] 2019-02-08 00:47
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/error-scan-results-for-php-7-1-compatibility/#p8700#spEditFormAnchor

**Comment by michaeltorbert** [comment] 2019-02-13 16:52
Reported by "sam sam" via email

**Closed** 2019-02-15 20:22 UTC
Labels: Has been reproduced, Priority | Medium
