### ISSUE TITLE
Fatal error: Cannot unset string offsets in all_in_one_seo_pack.php on line 328

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/all-in-one-seo-pack#1353] opened 2017-11-09 16:42 UTC
Reported here: https://wordpress.org/support/topic/fatal-error-string-offsets-in-all-in-one-seo-pack/

_I’m getting the following errors when I try to access my admin dashboard:

Warning: array_unshift() expects parameter 1 to be array, string given in ~/public_html/wp/wp-content/plugins/akismet/class.akismet-admin.php on line 89

Fatal error: Cannot unset string offsets in ~/public_html/wp/wp-content/plugins/all-in-one-seo-pack/all_in_one_seo_pack.php on line 328

My front-facing site is accessible but not the backend. Any help would be appreciated._

**Comment by EkoJr** [comment] 2017-11-11 00:08
I believe there is a conflict being caused by a different plugin that decided to use `'plugin_action_links'` filter instead of `'plugin_action_links_' . $plugin_name`, and in turn is replacing all other plugin action links, including Akismet.

I was unable to reproduce this, so I can't determine exactly what AIOSEOP can do, but I don't think a resolve can be found, considering it may be a different root issue.

**Comment by michaeltorbert** [comment] 2017-11-16 22:04
@EkoJr Most likely Jetpack or Akismet, based on reports.

**Comment by michaeltorbert** [comment] 2017-11-16 22:10
Also reported here: https://wordpress.org/support/topic/fatal-error-string-offsets-in-all-in-one-seo-pack/
Warning: array_unshift() expects parameter 1 to be array, string given in ~/public_html/wp/wp-content/plugins/akismet/class.akismet-admin.php on line 89

Fatal error: Cannot unset string offsets in ~/public_html/wp/wp-content/plugins/all-in-one-seo-pack/all_in_one_seo_pack.php on line 328

**Comment by michaeltorbert** [comment] 2017-11-16 22:27
https://github.com/Automattic/jetpack/issues/8164
Probably related.

**Comment by wpsmort** [comment] 2017-11-16 22:30
I have been able to reproduce this on a development site here - http://wordpress-128878-370533.cloudwaysapps.com/wp-admin/

I get these errors when I switched Jetpack to using my WP.com account, previously Jetpack was in Safe Mode as this is a duplicate of a live customer site:

Warning: array_unshift() expects parameter 1 to be array, string given in /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-content/plugins/akismet/class.akismet-admin.php on line 89

Fatal error: Uncaught Error: Cannot unset string offsets in /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-content/plugins/all-in-one-seo-pack-pro/all_in_one_seo_pack.php:323 Stack trace: #0 /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-includes/class-wp-hook.php(300): aiosp_add_action_links('', 'all-in-one-seo-...') #1 /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('', Array) #2 /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-callables.php(143): apply_filters('plugin_action_l...', '', 'all-in-one-seo-...', NULL, 'all') #3 /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-includes/class-wp-hook.php(298): Jetpack_Sync_Module_Callables->set_plugin_action_links('') #4 /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #5 /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-includes/plugin.php(453): in /home/128878.cloudwaysapps.com/bdqtvwzhbf/public_html/wp-content/plugins/all-in-one-seo-pack-pro/all_in_one_seo_pack.php on line 323

**Closed** 2017-11-17 01:56 UTC
Labels: Bug
