### ISSUE TITLE
ошибка - Warning: First parameter must either be an object or the name of an existing class in

### ISSUE THREAD

**Issue by moni777777** [semperfiwebdesign/all-in-one-seo-pack#3017] opened 2019-11-12 03:38 UTC
Warning: First parameter must either be an object or the name of an existing class in /home/admin/web/**************/public_html/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 132

Warning: First parameter must either be an object or the name of an existing class in /home/admin/web/*********/public_html/wp-content/plugins/all-in-one-seo-pack/inc/general/aioseop-robots-meta.php on line 136

после  обновления сегодня, выпадает такая ошибка

**Comment by arnaudbroes** [comment] 2019-11-12 07:36
@moni777777 thank you for reporting this. May I ask which page of your website this is happening on? Please provide us with a URL and the type of page it is in the WP admin panel.

**Comment by michaeltorbert** [comment] 2019-11-12 14:41
Duplicate of #3014

**Closed by michaeltorbert** 2019-11-12 14:41 UTC
Labels: Duplicate
