### ISSUE TITLE
Google Analytics missing

### ISSUE THREAD

**Issue by Techwork78** [semperfiwebdesign/all-in-one-seo-pack#2017] opened 2018-10-26 12:37 UTC
Hi
After upgrading from version 2.8 my Google Analytic ID is no longer inserted on my posts/pages. It is an issue in both version 2.9 and 2.9.1. If I roll back to version 2.8 it is working correct again.

When my ID is no longer inserted traffic is not logged in my Google Analytics account. Hope it can be fixed in future releases.

Best Regards
Thomas
https://techwork.dk

**Comment by michaeltorbert** [comment] 2018-10-26 12:49
Hi @Techwork78 
Thanks for reporting this. Unfortunately we're not able to reproduce this.
So that we can investigate and come up with a fix quickly, you can send us your login information to our secure form here: https://semperplugins.com/contact/support-login-information/

**Comment by arnaudbroes** [comment] 2018-10-27 10:37
FYI, I reached out to Thomas on his website to let him know we updated the issue.

**Comment by michaeltorbert** [comment] 2018-11-10 13:56
I'm closing this. If we're able to reproduce it or otherwise verify it isn't the CPT issue it can be reopened.

**Closed by michaeltorbert** 2018-11-10 13:56 UTC
Labels: Bug, Needs reproducing, Priority | High
